# Copilot pre-install steps for ephemeral dev environment
# This file helps GitHub Copilot Agents install project dependencies
# before attempting builds/tests/lints, improving PR quality and speed.

steps:
  - name: macOS — Install Rust toolchain
    if: runner.os == 'macOS'
    run: |
      if ! command -v rustc &> /dev/null; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
        source "$HOME/.cargo/env"
      fi
      rustup update stable
      rustc --version
      cargo --version

  - name: macOS — Install Node.js and npm
    if: runner.os == 'macOS'
    run: |
      if ! command -v node &> /dev/null; then
        brew install node
      fi
      node --version
      npm --version

  - name: macOS — Install system dependencies
    if: runner.os == 'macOS'
    run: |
      # Tauri system dependencies for macOS
      xcode-select --install || echo "Xcode command line tools already installed"

  - name: Linux — Install Rust toolchain
    if: runner.os == 'Linux'
    run: |
      if ! command -v rustc &> /dev/null; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
        source "$HOME/.cargo/env"
      fi
      rustup update stable
      rustc --version
      cargo --version

  - name: Linux — Install Node.js and npm
    if: runner.os == 'Linux'
    run: |
      if ! command -v node &> /dev/null; then
        sudo apt-get update
        sudo apt-get install -y nodejs npm
      fi
      node --version
      npm --version

  - name: Linux — Install Tauri system dependencies
    if: runner.os == 'Linux'
    run: |
      sudo apt-get update
      sudo apt-get install -y \
        libwebkit2gtk-4.0-dev \
        build-essential \
        curl \
        wget \
        file \
        libssl-dev \
        libgtk-3-dev \
        libayatana-appindicator3-dev \
        librsvg2-dev

  - name: Windows — Install Rust toolchain
    if: runner.os == 'Windows'
    run: |
      if (!(Get-Command rustc -ErrorAction SilentlyContinue)) {
        Invoke-WebRequest -Uri https://win.rustup.rs/x86_64 -OutFile rustup-init.exe
        .\rustup-init.exe -y --default-toolchain stable
        Remove-Item rustup-init.exe
        $env:Path += ";$env:USERPROFILE\.cargo\bin"
      }
      rustup update stable
      rustc --version
      cargo --version

  - name: Windows — Install Node.js and npm
    if: runner.os == 'Windows'
    run: |
      if (!(Get-Command node -ErrorAction SilentlyContinue)) {
        choco install nodejs -y
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
      }
      node --version
      npm --version

  - name: Windows — Install WebView2 (Tauri requirement)
    if: runner.os == 'Windows'
    run: |
      # WebView2 is typically pre-installed on Windows 11
      # If not, Tauri will handle it during development
      echo "WebView2 should be pre-installed on Windows 11"

  - name: Install Rust development tools
    run: |
      rustup component add rustfmt clippy
      cargo install sqlx-cli --no-default-features --features sqlite --locked || echo "sqlx-cli already installed or failed"

  - name: Install frontend dependencies
    run: |
      echo "Installing frontend dependencies..."
      npm install || echo "npm install failed"

  - name: Confirm repo tools
    run: |
      echo "=== Core Build Tools ==="
      echo "Rust: $(rustc --version 2>/dev/null || echo missing)"
      echo "Cargo: $(cargo --version 2>/dev/null || echo missing)"
      echo "Node: $(node --version 2>/dev/null || echo missing)"
      echo "npm: $(npm --version 2>/dev/null || echo missing)"
      echo ""
      echo "=== Rust Development Tools ==="
      echo "rustfmt: $(rustfmt --version 2>/dev/null || echo missing)"
      echo "clippy: $(cargo clippy --version 2>/dev/null || echo missing)"
      echo "sqlx-cli: $(cargo sqlx --version 2>/dev/null || echo missing)"
      echo ""
      echo "=== Project Structure ==="
      echo "Frontend: $(test -f package.json && echo present || echo missing)"
      echo "Backend: $(test -f src-tauri/Cargo.toml && echo present || echo missing)"
      echo "Database: $(test -d src-tauri/migrations && echo present || echo missing)"

  - name: Run quality checks
    run: |
      echo "=== Running Code Quality Checks ==="
      
      # Check TypeScript compilation
      echo "Checking TypeScript compilation..."
      npx tsc --noEmit || echo "⚠ TypeScript compilation failed"
      
      # Check Rust code compiles (skip on Linux without system deps in ephemeral env)
      if [ "$RUNNER_OS" != "Linux" ] || [ -f /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so ]; then
        echo "Checking Rust compilation..."
        cd src-tauri
        cargo check --all-features --all-targets || echo "⚠ Rust compilation check failed"
        
        # Run clippy for linting
        echo "Running clippy..."
        cargo clippy --workspace --all-features --all-targets -- -D warnings || echo "⚠ Clippy warnings found"
        
        # Check formatting
        echo "Checking code formatting..."
        cargo fmt --all -- --check || echo "⚠ Formatting issues found"
        
        # Run tests
        echo "Running tests..."
        cargo test --workspace --all-features || echo "⚠ Test failures found"
        
        cd ..
      else
        echo "Skipping Rust checks on Linux ephemeral environment (missing system deps)"
        echo "For full validation, run checks on a properly configured system"
      fi
      
      echo "=== Quality Checks Complete ==="

  - name: Database setup (development)
    run: |
      echo "Setting up development database..."
      cd src-tauri
      # SQLx will handle migrations on first run
      # This is just to verify the migration files exist
      if [ -d migrations ]; then
        echo "✓ Database migrations directory found"
        ls -la migrations/
      else
        echo "⚠ No migrations directory found"
      fi
      cd ..

  - name: Environment setup verification
    run: |
      echo "=== Environment Setup Verification ==="
      echo ""
      echo "✓ Rust toolchain installed and configured"
      echo "✓ Node.js and npm installed"
      echo "✓ Frontend dependencies installed"
      echo "✓ Rust components (rustfmt, clippy) installed"
      echo ""
      echo "Ready for development and testing!"
      echo ""
      echo "To start development:"
      echo "  npm run tauri:dev"
      echo ""
      echo "To build for production:"
      echo "  npm run tauri:build"
