# Copilot pre-install steps for ephemeral dev environment
# This file helps GitHub Copilot Agents install project dependencies
# before attempting builds/tests/lints, improving PR quality and speed.

steps:
  - name: Windows — Install Python and core tools
    if: runner.os == 'Windows'
    run: |
      python --version || echo "Python not found in PATH"
      pip install --upgrade pip
      echo "Python toolchain ready"

  - name: Windows — Install Playwright browsers
    if: runner.os == 'Windows'
    run: |
      pip install playwright
      playwright install chromium --with-deps || echo "Playwright install may need admin rights"

  - name: macOS — Install Python and core tools
    if: runner.os == 'macOS'
    run: |
      brew update
      brew install python@3.12 || echo "Python 3.12 already installed"
      python3 --version
      pip3 install --upgrade pip
      echo "Python toolchain ready"

  - name: macOS — Install Playwright browsers
    if: runner.os == 'macOS'
    run: |
      pip3 install playwright
      playwright install chromium --with-deps || echo "Playwright install may need permissions"

  - name: Linux — Install Python and core tools
    if: runner.os == 'Linux'
    run: |
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip python3-venv
      python3 --version
      pip3 install --upgrade pip
      echo "Python toolchain ready"

  - name: Linux — Install Playwright dependencies
    if: runner.os == 'Linux'
    run: |
      sudo apt-get install -y \
        libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 \
        libcups2 libdrm2 libdbus-1-3 libxkbcommon0 libxcomposite1 \
        libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2
      pip3 install playwright
      playwright install chromium --with-deps || echo "Playwright install may need permissions"

  - name: Install JobSentinel package with all extras
    run: |
      pip install -e .[dev,resume,ml,mcp,llm] || echo "Some optional dependencies may have failed"

  - name: Verify core dependencies
    run: |
      python -c "import pytest; print(f'pytest: {pytest.__version__}')"
      python -c "import fastapi; print(f'fastapi: {fastapi.__version__}')"
      python -c "import playwright; print(f'playwright: {playwright.__version__}')"
      python -c "import sqlalchemy; print(f'sqlalchemy: {sqlalchemy.__version__}')"
      python -c "import pydantic; print(f'pydantic: {pydantic.__version__}')"
      echo "Core dependencies verified"

  - name: Verify optional dependencies (best effort)
    run: |
      python -c "import spacy; print(f'spacy: {spacy.__version__}')" || echo "spacy not installed (resume extra)"
      python -c "import sentence_transformers; print(f'sentence-transformers: {sentence_transformers.__version__}')" || echo "sentence-transformers not installed (ml extra)"
      python -c "import openai; print(f'openai: {openai.__version__}')" || echo "openai not installed (llm extra)"
      python -c "import mcp; print(f'mcp: {mcp.__version__}')" || echo "mcp not installed (mcp extra)"
      echo "Optional dependencies check complete"

  - name: Verify linting and testing tools
    run: |
      ruff --version || echo "ruff not found"
      mypy --version || echo "mypy not found"
      black --version || echo "black not found"
      bandit --version || echo "bandit not found"
      pytest --version || echo "pytest not found"

  - name: Setup test database
    run: |
      python -c "
      from pathlib import Path
      import sqlite3
      db_path = Path('test_jobs.db')
      if not db_path.exists():
          conn = sqlite3.connect(str(db_path))
          conn.execute('CREATE TABLE IF NOT EXISTS jobs (id INTEGER PRIMARY KEY)')
          conn.commit()
          conn.close()
          print('Test database created')
      else:
          print('Test database already exists')
      "

  - name: Confirm repo tools and environment
    run: |
      echo "=== Core Build Tools ==="
      echo "Python: $(python --version 2>&1 || echo missing)"
      echo "pip: $(pip --version 2>&1 | head -1 || echo missing)"
      echo ""
      echo "=== Testing & Quality Tools ==="
      echo "pytest: $(pytest --version 2>&1 | head -1 || echo missing)"
      echo "ruff: $(ruff --version 2>&1 || echo missing)"
      echo "mypy: $(mypy --version 2>&1 || echo missing)"
      echo "black: $(black --version 2>&1 || echo missing)"
      echo "bandit: $(bandit --version 2>&1 || echo missing)"
      echo ""
      echo "=== Key Dependencies ==="
      python -c "
      import sys
      packages = ['fastapi', 'playwright', 'sqlalchemy', 'pydantic', 'beautifulsoup4']
      for pkg in packages:
          try:
              mod = __import__(pkg)
              ver = getattr(mod, '__version__', 'unknown')
              print(f'{pkg}: {ver}')
          except ImportError:
              print(f'{pkg}: missing')
      "
      echo ""
      echo "=== Optional Features ==="
      python -c "
      import sys
      packages = ['spacy', 'sentence_transformers', 'openai', 'anthropic', 'mcp']
      for pkg in packages:
          try:
              mod = __import__(pkg)
              ver = getattr(mod, '__version__', 'unknown')
              print(f'{pkg}: {ver}')
          except ImportError:
              print(f'{pkg}: not installed (optional)')
      "
