version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    target-branch: "develop"
    reviewers:
      - "cboyd0319"
    assignees:
      - "cboyd0319"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Disable automerge for security - manual review required
    automerge: false
    # Group security updates for priority handling
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      development-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "flake8*"
          - "mypy*"
          - "bandit*"
          - "safety"
          - "pre-commit"
          - "semgrep"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    target-branch: "develop"
    reviewers:
      - "cboyd0319"
    assignees:
      - "cboyd0319"
    labels:
      - "github-actions"
      - "dependencies"
      - "security"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Disable automerge for manual security review
    automerge: false
