repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=120]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=120]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120, --exclude=.venv]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: [-r, ., -x, ./.venv, --quiet, -f, json, -o, bandit-report.json]
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional]
        additional_dependencies: [types-requests, types-setuptools]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c=config/.yamllint.yml]

  - repo: https://github.com/pycqa/safety
    rev: 3.0.1
    hooks:
      - id: safety
        args: [--short-report, --ignore=70612]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: [--skip, "*.json,*.log,.git,.venv"]

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        args: [--score=n, --disable=all, --enable=W, E, F]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --ignore-init-module-imports]

  - repo: local
    hooks:
      - id: precommit-security-scan
        name: Pre-commit Security Scan
        entry: scripts/precommit-security-scan.sh
        language: script
        pass_filenames: false
        always_run: true
        stages: [manual, push]

      - id: basic-security-scan
        name: Basic Security Scan (Fast)
        entry: scripts/precommit-security-scan.sh
        language: script
        pass_filenames: false
        always_run: true
        stages: [commit]
