# CodeCov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 85%
        threshold: 1%
        if_ci_failed: error
    
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false

ignore:
  - "deploy/common/tests/**"
  - "deploy/common/examples/**"
  - "deploy/common/scripts/**"
  - "**/__pycache__/**"
  - "**/migrations/**"
  - "deploy/local/**"
  - "deploy/cloud/**"
