import { readFileSync } from "node:fs";
import { join } from "node:path";
import { hasTechnicalFirstFallbackCopy } from "./product-copy/technical-first-fallback.mjs";
import { getTechnicalFirstPreflightResult } from "./product-copy/technical-first-preflight.mjs";
import { getTechnicalFirstDocsResult } from "./product-copy/technical-first-docs.mjs";
import { getTechnicalFirstUiResult } from "./product-copy/technical-first-ui.mjs";
export {
  hasApplicationAssistAutomationFraming,
  hasEngineerFirstResumeTemplateCopy,
  hasStaleResumeOptimizerFraming,
} from "./product-copy/resume-and-application.mjs";
export {
  hasFeedbackLocalReportDrift,
  hasFeedbackSetupJargon,
  hasFeedbackTechnicalCompanyLabels,
  hasLegacyPreferenceListCopy,
  hasNonProtectivePayFloorRecoveryCopy,
  hasNonProtectiveScoreCopy,
  hasOverconfidentGhostCopy,
  hasOverconfidentPayGuidance,
  hasRawErrorBoundaryDetails,
  hasRawFeedbackDebugEventDetails,
  hasRawProblemHistoryContextDetails,
  hasTechnicalRecoveryCopy,
} from "./product-copy/trust-and-recovery.mjs";

const technicalFirstUserCopyPaths = new Set([
  ".github/ISSUE_TEMPLATE/bug_report.yml",
  ".github/ISSUE_TEMPLATE/feature_request.yml",
  ".github/ISSUE_TEMPLATE/question.yml",
  ".github/ISSUE_TEMPLATE/scraper_issue.yml",
  "docs/ROADMAP.md",
  "README.md",
  "docs/features/browser-import.md",
  "src/features/settings/sources/browser-import/BrowserImportControls.tsx",
  "src/features/settings/sources/browser-import/BrowserImportSection.tsx",
  "src/features/applications/CoverLetterTemplates.tsx",
  "src/features/search-links/SearchLinksForm.tsx",
  "src/features/search-links/SearchLinksPage.tsx",
  "src/features/search-links/SearchLinksResults.tsx",
  "src/app/errors/ErrorBoundary.tsx",
  "src/features/settings/support/ErrorLogPanel.tsx",
  "src/features/dashboard/components/ScoreBreakdownModal.tsx",
  "src/ui/score-display/ScoreDisplay.tsx",
  "src/ui/score-display/internal/scoreReasons.ts",
  "src/features/settings/sources/health/ScraperHealthDashboard.tsx",
  "src/features/settings/sources/health/scraperHealthDashboardModel.ts",
  "src/features/onboarding/CareerProfileSelector.tsx",
  "src/features/dashboard/components/JobImportModal.tsx",
  "src/features/dashboard/components/JobCard.tsx",
  "src/features/dashboard/components/jobCardGuidance.ts",
  "src/features/resumes/builder/AtsLiveScorePanel.tsx",
  "src/features/applications/AnalyticsPanel.tsx",
  "src/features/dashboard/components/DashboardWidgets.tsx",
  "src/shared/externalAi/internal/aiGateway.ts",
  "src/features/settings/notifications/NotificationPreferences.tsx",
  "src/features/resumes/builder/steps/ContactStep.tsx",
  "src/features/resumes/builder/steps/EducationStep.tsx",
  "src/features/resumes/builder/steps/ExperienceStep.tsx",
  "src/features/resumes/builder/steps/SkillsStep.tsx",
  "src/features/resumes/builder/steps/SummaryStep.tsx",
  "src/features/applications/InterviewScheduler.tsx",
  "src/app/commands/CommandPalette.tsx",
  "src/app/commands/KeyboardShortcutsHelp.tsx",
  "src/features/market/LocationHeatmap.tsx",
  "src/features/market/MarketHeader.tsx",
  "src/features/market/MarketPanels.tsx",
  "src/features/market/MarketSnapshotCard.tsx",
  "src/app/Navigation.tsx",
  "src/features/application-assist/ApplyButton.tsx",
  "src/features/application-assist/ApplicationPreview.tsx",
  "src/features/application-assist/ProfileForm.tsx",
  "src/features/application-assist/ScreeningAnswerSuggestions.tsx",
  "src/features/application-assist/ScreeningAnswersForm.tsx",
  "src/features/settings/support/feedback/DebugInfoPreview.tsx",
  "src/features/settings/support/feedback/FeedbackModal.tsx",
  "src/features/settings/support/feedback/SubmitOptions.tsx",
  "src/features/settings/support/feedback/SuccessScreen.tsx",
  "src/features/settings/support/feedback/useFeedback.ts",
  "src/dev-runtime/features/application-assist/atsPlatform.ts",
  "src/features/market/mockHandlers.ts",
  "src/dev-runtime/features/resumes/resumeAnalysisRunner.ts",
  "src/dev-runtime/features/resumes/resumeBulletPrompts.ts",
  "src/dev-runtime/features/resumes/resumeBuilder.ts",
  "src/dev-runtime/features/resumes/resumeKeywordMatching.ts",
  "src/dev-runtime/features/resumes/resumeRequirementReview.ts",
  "src/dev-runtime/mocks/handlers.ts",
  "src/app/providers/UndoProvider.tsx",
  "src/app/keyboard/KeyboardShortcutsProvider.tsx",
  "src-tauri/src/ipc/errors.rs",
  "src-tauri/src/ipc/bookmarklet.rs",
  "crates/jobsentinel-assistance/src/automation/error.rs",
  "crates/jobsentinel-documents/src/ats_analyzer.rs",
  "crates/jobsentinel-documents/src/ats_analyzer/bullet_prompts.rs",
  "crates/jobsentinel-storage/src/resume/matcher.rs",
  "crates/jobsentinel-storage/src/salary/analyzer.rs",
  "crates/jobsentinel-sources/src/scrapers/error.rs",
  "crates/jobsentinel-storage/migrations/00000000000000_initial_schema.sql",
  "src/platform/tauri/commandClient.ts",
  "src/features/resumes/library/ResumeLibraryPage.tsx",
  "src/features/dashboard/hooks/useDashboardAutoRefresh.ts",
  "src/features/dashboard/hooks/useDashboardJobOps.ts",
  "src/features/dashboard/hooks/useDashboardSavedSearches.ts",
  "src/features/resumes/matching/ResumeMatchPage.tsx",
  "src/features/applications/ApplicationsPage.tsx",
  "src/features/application-assist/ApplicationProfilePage.tsx",
  "src/features/dashboard/DashboardPage.tsx",
  "src/features/dashboard/dashboardErrorCopy.ts",
  "src/features/market/errorCopy.ts",
  "src/features/dashboard/components/DashboardHeader.tsx",
  "src/features/dashboard/components/noJobsEmptyStateCopy.ts",
  "src/features/dashboard/components/DashboardFiltersBar.tsx",
  "src/features/dashboard/components/filterLabels.ts",
  "src/features/dashboard/components/QuickActions.tsx",
  "src/features/market/MarketPage.tsx",
  "src/features/resumes/builder/ResumeBuilderPage.tsx",
  "src/features/resumes/builder/ResumeBuilderPreviewStep.tsx",
  "src/features/resumes/builder/ResumeBuilderVisuals.tsx",
  "src/features/resumes/library/ResumeLibraryDropdown.tsx",
  "src/features/resumes/matching/ResumeMatchJobWordsOverview.tsx",
  "src/features/resumes/matching/ResumeMatchResultsPanel.tsx",
  "src/features/resumes/library/ResumeTextPreviewModal.tsx",
  "src/features/resumes/library/resumePageModel.ts",
  "src/features/resumes/matching/resumeMatchModel.ts",
  "src/features/salary/NegotiationNotesCard.tsx",
  "src/features/salary/OfferReviewPanel.tsx",
  "src/features/salary/SalaryEvidenceCard.tsx",
  "src/features/salary/SalaryPage.tsx",
  "src/features/salary/SalarySearchCard.tsx",
  "src/features/settings/sources/SettingsConnectedJobSource.tsx",
  "src/features/settings/sources/SettingsJobSourcesSection.tsx",
  "src/features/settings/matching/SettingsResumeMatchingSection.tsx",
  "src/features/settings/search/SettingsPostingRiskSection.tsx",
  "src/features/settings/shared/SettingsSecurityBadge.tsx",
  "src/features/settings/support/SettingsSupportSections.tsx",
  "src/features/settings/SettingsPage.tsx",
  "src/features/onboarding/SetupWizard.tsx",
  "src/features/onboarding/SetupWizardSearchSummary.tsx",
  "src/features/onboarding/setupWizardPreferences.ts",
  "src/shared/errorReporting/messages.ts",
  "src/shared/errorReporting/safeToastCopy.ts",
  "src/features/application-assist/applicationFormValidation.ts",
  "src/features/settings/credentials/notificationConnectionValidation.ts",
  "src/shared/validation/contactFieldValidation.ts",
  "src/shared/jobSourceGuidance.ts",
  "tests/e2e/playwright/application-tracking.spec.ts",
  "tests/e2e/playwright/page-objects/ApplicationsPage.ts",
  "docs/features/application-tracking.md",
  "docs/features/ghost-detection.md",
  "docs/features/hiring-trends.md",
  "docs/features/smart-scoring.md",
  "docs/features/notifications.md",
  "docs/features/application-assist.md",
  "docs/features/saved-secrets.md",
  "docs/features/json-resume-import.md",
  "docs/features/remote-preference-scoring.md",
  "docs/features/resume-builder.md",
  "docs/features/resume-matcher.md",
  "docs/features/pay-protection.md",
  "docs/features/job-source-status.md",
  "docs/features/job-sources.md",
  "docs/features/synonym-matching.md",
  "docs/features/user-data-management.md",
  "docs/harness/readme-information-design.md",
  "docs/user/DEEP_LINKS.md",
  "docs/user/QUICK_START.md",
  "CODE_OF_CONDUCT.md",
  "PRIVACY.md",
  "SECURITY.md",
]);
export function hasTechnicalFirstUserCopy(root, path) {
  const preflightResult = getTechnicalFirstPreflightResult(root, path);
  if (preflightResult !== undefined) {
    return preflightResult;
  }

  if (!technicalFirstUserCopyPaths.has(path)) {
    return false;
  }

  const text = readFileSync(join(root, path), "utf8");

  const docsResult = getTechnicalFirstDocsResult(path, text);
  if (docsResult !== undefined) {
    return docsResult;
  }

  const uiResult = getTechnicalFirstUiResult(path, text);
  if (uiResult !== undefined) {
    return uiResult;
  }

  return hasTechnicalFirstFallbackCopy(text);
}
