name: Bug Report
description: Report a bug or issue with JobSentinel
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us fix it quickly.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have searched existing [issues](https://github.com/cboyd0319/JobSentinel/issues) and this is not a duplicate
          required: true
        - label: I have read the [FAQ](https://github.com/cboyd0319/JobSentinel#frequently-asked-questions-faq)
          required: true
        - label: I am using the latest version of JobSentinel
          required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 11
        - Windows 11 (Insider)
        - macOS 26.1 (Tahoe)
        - macOS 26.0 or older
        - Linux (unsupported)
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: JobSentinel Version
      description: What version of JobSentinel are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: JobSentinel crashes when I click "Search Now"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Open JobSentinel
        2. Click on "Search Now"
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: JobSentinel should start scraping jobs
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: App crashed with error message
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Run JobSentinel with `RUST_LOG=debug` and paste relevant error messages here.
      placeholder: |
        [ERROR] Failed to scrape Greenhouse: connection timeout
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration (if relevant)
      description: Paste relevant parts of your config.json (remove sensitive data like webhook URLs)
      placeholder: |
        {
          "title_allowlist": ["Engineer"],
          "salary_floor_usd": 150000
        }
      render: json

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
