name: Feature Request
description: Suggest an improvement or new feature
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        We'd love to hear your ideas for making JobSentinel better!

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or pain point
      placeholder: "I often find myself needing to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe your proposed solution
      description: What would you like to see?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Any other approaches you've thought about?
