---
name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: feature-request
    attributes:
      label: Feature Description
      description: What feature or enhancement would you like to see?
      placeholder: "Example: Add support for scraping Indeed.com job listings"
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this needed?
      description: What problem does this solve or what value does it add?
      placeholder: "Example: Indeed is a major job board with thousands of listings that would be valuable for job search automation."
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Proposed Implementation (Optional)
      description: If you have ideas on how to implement this, share them here.
      placeholder: "Example: Create a new scraper in sources/indeed.py using Playwright to handle their dynamic content."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Are there any alternative solutions or workarounds you've considered?
      placeholder: "Example: Manually checking Indeed daily, but this defeats the purpose of automation."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and feature requests to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals (privacy-first, local-first job automation)
          required: true
