name: Feature Request
description: Suggest a new feature for JobSentinel
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea in detail.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have searched existing [issues](https://github.com/cboyd0319/JobSentinel/issues) and this is not a duplicate
          required: true
        - label: I have checked the [project roadmap](https://github.com/cboyd0319/JobSentinel/blob/main/V1_COMPLETION_STATUS.md)
          required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New job board scraper
        - UI/UX improvement
        - New notification method
        - Configuration option
        - Performance improvement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when I have to manually check multiple job boards...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: Add support for scraping LinkedIn jobs...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I considered using browser automation instead...

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples, mockups, or references to similar features in other tools.
      placeholder: |
        Similar to how Indeed does X...
        [Screenshot or link]

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Critical - blocking my use of JobSentinel
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help test this feature
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
