# Docker Compose for isolated MCP servers
# Usage: docker-compose -f docker/docker-compose.mcp.yml up
#
# Security features:
# - Read-only root filesystem
# - No network access (except whitelisted servers)
# - Resource limits (CPU, memory)
# - Non-root user
# - Minimal capabilities

version: '3.8'

services:
  # JobsWithGPT MCP Server (low risk - read-only API)
  jobswithgpt:
    build:
      context: ..
      dockerfile: docker/mcp-sandbox.dockerfile
    container_name: mcp-jobswithgpt
    user: "1000:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - mcp-network
    environment:
      - MCP_SERVER_NAME=jobswithgpt
      - ALLOWED_DOMAINS=jobswithgpt.com
    volumes:
      - ../sources:/app/sources:ro
      - ../logs:/data/logs:rw
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped

  # Reed Jobs MCP Server (low risk - official API)
  reed:
    build:
      context: ..
      dockerfile: docker/mcp-sandbox.dockerfile
    container_name: mcp-reed
    user: "1000:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - mcp-network
    environment:
      - MCP_SERVER_NAME=reed
      - REED_API_KEY=${REED_API_KEY}
      - ALLOWED_DOMAINS=reed.co.uk
    volumes:
      - ../sources:/app/sources:ro
      - ../logs:/data/logs:rw
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped

  # JobSpy MCP Server (MEDIUM RISK - aggressive scraping)
  # NOTE: Use with caution. Disable network access to prevent abuse.
  jobspy:
    build:
      context: ..
      dockerfile: docker/mcp-sandbox.dockerfile
    container_name: mcp-jobspy
    user: "1000:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    # NO NETWORK - uncomment `networks` only if needed and audited
    # networks:
    #   - mcp-network
    network_mode: none  # COMPLETELY ISOLATED
    environment:
      - MCP_SERVER_NAME=jobspy
      - ALLOWED_DOMAINS=indeed.com,glassdoor.com,ziprecruiter.com
    volumes:
      - ../sources:/app/sources:ro
      - ../logs:/data/logs:rw
      - ./jobspy-cache:/data/cache:rw  # Cached scraper data
    tmpfs:
      - /tmp:noexec,nosuid,size=200m
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped

networks:
  mcp-network:
    driver: bridge
    internal: false  # Set to `true` to block all external access
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  jobspy-cache:
    driver: local
