import type { CareerProfile } from "./careerProfileTaxonomy";

export const BUSINESS_CAREER_PROFILES: CareerProfile[] = [
  {
    id: "sales-business-dev",
    name: "Sales & Business",
    description: "Account executives, BDRs, and sales managers",
    icon: "briefcase",
    salaryRange: "$60k - $200k+",
    salaryFloor: 60000,
    titleAllowlist: [
      "Account Executive",
      "Senior Account Executive",
      "Enterprise Account Executive",
      "Sales Development Representative",
      "SDR",
      "BDR",
      "Business Development",
      "Sales Manager",
      "Regional Sales Manager",
      "Director of Sales",
      "VP of Sales",
      "Customer Success Manager",
      "Account Manager",
      "Partnerships Manager",
      "Sales Engineer",
      "Solutions Engineer",
      "Pre-Sales Engineer",
    ],
    titleBlocklist: ["Intern", "Internship", "Door to Door", "Canvasser"],
    keywordsBoost: [
      "B2B Sales",
      "SaaS Sales",
      "Enterprise Sales",
      "Solution Selling",
      "Salesforce",
      "HubSpot",
      "Outreach",
      "Pipeline Management",
      "Quota Attainment",
      "Prospecting",
      "Cold Calling",
      "Negotiation",
      "Customer Relationship",
      "Account Management",
      "Upselling",
    ],
    keywordsExclude: [
      "commission only",
      "door to door",
      "MLM",
      "network marketing",
    ],
    locationPreferences: {
      allow_remote: true,
      allow_hybrid: true,
      allow_onsite: true,
    },
    sampleTitles: ["Account Executive", "Sales Manager", "BDR"],
  },
  {
    id: "hr-recruiting",
    name: "HR & People",
    description: "Recruiters, HR business partners, and people ops",
    icon: "users",
    salaryRange: "$60k - $150k",
    salaryFloor: 60000,
    titleAllowlist: [
      "Recruiter",
      "Senior Recruiter",
      "Recruiting Manager",
      "Talent Acquisition",
      "Sourcer",
      "Recruiting Coordinator",
      "HR Business Partner",
      "HRBP",
      "HR Manager",
      "Director of HR",
      "VP of HR",
      "CHRO",
      "People Operations",
      "People Partner",
      "HR Generalist",
      "Compensation Analyst",
      "Benefits Manager",
      "Learning & Development",
      "Employee Relations",
      "Onboarding Specialist",
      "Technical Recruiter",
    ],
    titleBlocklist: ["Intern", "Internship", "Junior", "Entry Level"],
    keywordsBoost: [
      "Full-cycle Recruiting",
      "Sourcing",
      "Employee Relations",
      "Onboarding",
      "Benefits",
      "Compensation",
      "HRIS",
      "Performance Management",
      "Learning & Development",
      "People Operations",
      "Employer Branding",
      "Diversity & Inclusion",
      "D&I",
      "Workday",
      "Greenhouse",
      "Lever",
      "LinkedIn Recruiter",
      "Technical Recruiting",
    ],
    keywordsExclude: ["staffing agency", "temp agency"],
    locationPreferences: {
      allow_remote: true,
      allow_hybrid: true,
      allow_onsite: true,
    },
    sampleTitles: ["Recruiter", "HRBP", "People Operations"],
  },
  {
    id: "finance-accounting",
    name: "Finance & Accounting",
    description: "FP&A, controllers, accountants, and analysts",
    icon: "calculator",
    salaryRange: "$60k - $180k",
    salaryFloor: 60000,
    titleAllowlist: [
      "Financial Analyst",
      "Senior Financial Analyst",
      "FP&A Analyst",
      "FP&A Manager",
      "Accountant",
      "Senior Accountant",
      "Staff Accountant",
      "CPA",
      "Controller",
      "Assistant Controller",
      "Director of Finance",
      "VP of Finance",
      "CFO",
      "Accounts Payable",
      "Accounts Receivable",
      "Billing Specialist",
      "Tax Manager",
      "Audit Manager",
      "Internal Auditor",
    ],
    titleBlocklist: ["Intern", "Internship", "Junior", "Entry Level"],
    keywordsBoost: [
      "Financial Modeling",
      "Budgeting",
      "Forecasting",
      "Variance Analysis",
      "GAAP",
      "SEC Reporting",
      "Audit",
      "Tax",
      "Revenue Recognition",
      "Excel",
      "NetSuite",
      "QuickBooks",
      "SAP",
      "Oracle Financials",
      "Month-end Close",
      "Financial Statements",
      "Cash Flow",
    ],
    keywordsExclude: [],
    locationPreferences: {
      allow_remote: true,
      allow_hybrid: true,
      allow_onsite: true,
    },
    sampleTitles: ["Financial Analyst", "Controller", "FP&A Manager"],
  },
  {
    id: "project-operations",
    name: "Operations & PM",
    description: "Project managers, program managers, and operations",
    icon: "clipboard",
    salaryRange: "$70k - $160k",
    salaryFloor: 70000,
    titleAllowlist: [
      "Project Manager",
      "Senior Project Manager",
      "Technical Project Manager",
      "Program Manager",
      "Senior Program Manager",
      "Portfolio Manager",
      "Operations Manager",
      "Director of Operations",
      "VP of Operations",
      "COO",
      "Business Operations",
      "Strategy & Operations",
      "Chief of Staff",
      "Scrum Master",
      "Agile Coach",
      "Delivery Manager",
    ],
    titleBlocklist: ["Intern", "Internship", "Junior", "Entry Level"],
    keywordsBoost: [
      "Project Management",
      "Program Management",
      "Agile",
      "Scrum",
      "Kanban",
      "PMP",
      "PRINCE2",
      "Stakeholder Management",
      "Risk Management",
      "Jira",
      "Asana",
      "Monday.com",
      "Confluence",
      "Process Improvement",
      "Change Management",
      "Cross-functional",
    ],
    keywordsExclude: [],
    locationPreferences: {
      allow_remote: true,
      allow_hybrid: true,
      allow_onsite: true,
    },
    sampleTitles: ["Project Manager", "Program Manager", "Operations Manager"],
  },
  {
    id: "content-copywriting",
    name: "Content & Writing",
    description: "Content writers, copywriters, and editors",
    icon: "pen",
    salaryRange: "$55k - $130k",
    salaryFloor: 55000,
    titleAllowlist: [
      "Content Writer",
      "Senior Content Writer",
      "Copywriter",
      "Senior Copywriter",
      "Content Strategist",
      "Content Manager",
      "Content Marketing Manager",
      "Editor",
      "Managing Editor",
      "Editorial Manager",
      "Technical Writer",
      "UX Writer",
      "UX Copywriter",
      "Social Media Manager",
      "Communications Manager",
      "PR Manager",
    ],
    titleBlocklist: [
      "Intern",
      "Internship",
      "Junior",
      "Entry Level",
      "Freelance",
      "Contract",
    ],
    keywordsBoost: [
      "Content Strategy",
      "SEO Writing",
      "B2B Content",
      "SaaS Writing",
      "Technical Writing",
      "UX Writing",
      "Microcopy",
      "Brand Voice",
      "Editorial Calendar",
      "CMS",
      "WordPress",
      "Contentful",
      "Email Copy",
      "Landing Pages",
      "Conversion",
      "Engagement",
    ],
    keywordsExclude: ["ghostwriting only", "content mill", "pay per article"],
    locationPreferences: {
      allow_remote: true,
      allow_hybrid: true,
      allow_onsite: true,
    },
    sampleTitles: ["Content Writer", "UX Writer", "Content Strategist"],
  },
];
