import type { CareerProfile } from "./careerProfileModel";

export const TECHNICAL_CAREER_PROFILES: CareerProfile[] = [
  {
    id: "software-engineering",
    name: "Software & Tech",
    description: "Engineers, developers, DevOps, and SRE roles",
    icon: "code",
    salaryRange: "$100k - $250k",
    salaryFloor: 100000,
    titleAllowlist: [
      "Software Engineer",
      "Senior Software Engineer",
      "Staff Software Engineer",
      "Principal Engineer",
      "Backend Engineer",
      "Frontend Engineer",
      "Full Stack Engineer",
      "DevOps Engineer",
      "SRE",
      "Site Reliability Engineer",
      "Platform Engineer",
      "Infrastructure Engineer",
      "Cloud Engineer",
      "Systems Engineer",
      "Engineering Manager",
      "Director of Engineering",
      "VP of Engineering",
      "CTO",
    ],
    titleBlocklist: [
      "Intern",
      "Internship",
      "Junior",
      "Entry Level",
      "Recruiter",
      "Sales",
    ],
    keywordsBoost: [
      "Python",
      "JavaScript",
      "TypeScript",
      "Go",
      "Rust",
      "Java",
      "Kubernetes",
      "AWS",
      "GCP",
      "Azure",
      "Docker",
      "Terraform",
      "React",
      "Node.js",
      "PostgreSQL",
      "Redis",
      "Kafka",
      "gRPC",
      "GraphQL",
      "REST API",
      "Microservices",
      "Distributed Systems",
      "CI/CD",
      "Agile",
    ],
    keywordsExclude: ["clearance required", "polygraph"],
    locationPreferences: {
      allow_remote: true,
      allow_hybrid: true,
      allow_onsite: false,
    },
    sampleTitles: ["Software Engineer", "DevOps Engineer", "Staff Engineer"],
  },
  {
    id: "cybersecurity",
    name: "Security",
    description: "Security engineers, analysts, and penetration testers",
    icon: "shield",
    salaryRange: "$100k - $250k",
    salaryFloor: 130000,
    titleAllowlist: [
      "Security Engineer",
      "Senior Security Engineer",
      "Staff Security Engineer",
      "Application Security Engineer",
      "AppSec Engineer",
      "Product Security Engineer",
      "Cloud Security Engineer",
      "Network Security Engineer",
      "Security Architect",
      "Security Analyst",
      "SOC Analyst",
      "Threat Analyst",
      "Incident Response",
      "Penetration Tester",
      "Red Team",
      "Blue Team",
      "Security Consultant",
      "Security Manager",
      "CISO",
      "Head of Security",
      "Director of Security",
    ],
    titleBlocklist: [
      "Intern",
      "Internship",
      "Junior",
      "Entry Level",
      "Physical Security",
      "Security Guard",
    ],
    keywordsBoost: [
      "Application Security",
      "AppSec",
      "Cloud Security",
      "AWS Security",
      "Kubernetes Security",
      "SAST",
      "DAST",
      "Threat Modeling",
      "Penetration Testing",
      "Vulnerability Assessment",
      "Zero Trust",
      "IAM",
      "SIEM",
      "SOAR",
      "Incident Response",
      "SOC 2",
      "ISO 27001",
      "NIST",
      "OWASP",
      "Burp Suite",
    ],
    keywordsExclude: [
      "security clearance required",
      "TS/SCI",
      "polygraph",
      "physical security",
    ],
    locationPreferences: {
      allow_remote: true,
      allow_hybrid: true,
      allow_onsite: false,
    },
    sampleTitles: [
      "Security Engineer",
      "AppSec Engineer",
      "Penetration Tester",
    ],
  },
  {
    id: "data-science",
    name: "Data & Analytics",
    description: "Data scientists, ML engineers, and analysts",
    icon: "chart",
    salaryRange: "$90k - $220k",
    salaryFloor: 90000,
    titleAllowlist: [
      "Data Scientist",
      "Senior Data Scientist",
      "Staff Data Scientist",
      "Machine Learning Engineer",
      "ML Engineer",
      "AI Engineer",
      "Data Analyst",
      "Senior Data Analyst",
      "Business Intelligence Analyst",
      "Data Engineer",
      "Analytics Engineer",
      "Research Scientist",
      "Quantitative Analyst",
      "Data Science Manager",
      "Head of Data",
    ],
    titleBlocklist: ["Intern", "Internship", "Junior", "Entry Level"],
    keywordsBoost: [
      "Python",
      "SQL",
      "Machine Learning",
      "Deep Learning",
      "TensorFlow",
      "PyTorch",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Statistics",
      "A/B Testing",
      "Data Visualization",
      "Tableau",
      "Looker",
      "dbt",
      "Airflow",
      "Spark",
      "Databricks",
      "Snowflake",
      "BigQuery",
      "Experimentation",
    ],
    keywordsExclude: [],
    locationPreferences: {
      allow_remote: true,
      allow_hybrid: true,
      allow_onsite: false,
    },
    sampleTitles: ["Data Scientist", "ML Engineer", "Data Analyst"],
  },
  {
    id: "product-management",
    name: "Product & Design",
    description: "Product managers, designers, and UX researchers",
    icon: "lightbulb",
    salaryRange: "$100k - $200k",
    salaryFloor: 100000,
    titleAllowlist: [
      "Product Manager",
      "Senior Product Manager",
      "Principal Product Manager",
      "Group Product Manager",
      "Director of Product",
      "VP of Product",
      "CPO",
      "Technical Product Manager",
      "Product Owner",
      "Product Designer",
      "Senior Product Designer",
      "Staff Designer",
      "UX Designer",
      "UI Designer",
      "UX Researcher",
      "Design Manager",
    ],
    titleBlocklist: [
      "Intern",
      "Internship",
      "Junior",
      "Entry Level",
      "Associate",
    ],
    keywordsBoost: [
      "Product Strategy",
      "Roadmap",
      "Agile",
      "Scrum",
      "User Research",
      "A/B Testing",
      "Data-Driven",
      "Cross-functional",
      "Stakeholder Management",
      "Figma",
      "User Experience",
      "Design Systems",
      "Prototyping",
      "Customer Discovery",
      "Product Analytics",
      "OKRs",
      "Go-to-Market",
    ],
    keywordsExclude: [],
    locationPreferences: {
      allow_remote: true,
      allow_hybrid: true,
      allow_onsite: false,
    },
    sampleTitles: ["Product Manager", "Product Designer", "UX Researcher"],
  },
  {
    id: "seo-digital-marketing",
    name: "Marketing & SEO",
    description: "SEO managers, growth marketers, and e-commerce",
    icon: "trending",
    salaryRange: "$70k - $150k",
    salaryFloor: 70000,
    titleAllowlist: [
      "SEO Manager",
      "Senior SEO Manager",
      "Director of SEO",
      "Head of SEO",
      "SEO Specialist",
      "SEO Analyst",
      "Technical SEO",
      "Digital Marketing Manager",
      "Growth Marketing Manager",
      "Performance Marketing",
      "E-Commerce Manager",
      "E-Commerce Director",
      "Marketplace Manager",
      "Paid Media Manager",
      "PPC Manager",
      "SEM Manager",
      "Marketing Manager",
      "Director of Marketing",
      "VP of Marketing",
      "CMO",
    ],
    titleBlocklist: ["Intern", "Internship", "Junior", "Entry Level"],
    keywordsBoost: [
      "SEO",
      "SEM",
      "PPC",
      "Google Analytics",
      "Google Ads",
      "Semrush",
      "Ahrefs",
      "Content Strategy",
      "Link Building",
      "Technical SEO",
      "On-page SEO",
      "Shopify",
      "Salesforce Commerce Cloud",
      "Magento",
      "E-commerce",
      "Conversion Rate Optimization",
      "A/B Testing",
      "Email Marketing",
      "Marketing Automation",
      "HubSpot",
      "Marketo",
      "Klaviyo",
    ],
    keywordsExclude: ["MLM", "network marketing", "commission only"],
    locationPreferences: {
      allow_remote: true,
      allow_hybrid: true,
      allow_onsite: true,
    },
    sampleTitles: ["SEO Manager", "Growth Marketing", "E-Commerce Manager"],
  },
];
