import type { CareerProfile } from "./careerProfileModel";

export const GENERAL_CAREER_PROFILES: CareerProfile[] = [
  {
    id: "office-administration",
    name: "Office & Admin",
    description: "Administrative assistants, office managers, and coordinators",
    icon: "clipboard",
    salaryRange: "$40k - $95k",
    salaryFloor: 40000,
    titleAllowlist: [
      "Administrative Assistant",
      "Admin Assistant",
      "Executive Assistant",
      "Office Assistant",
      "Office Administrator",
      "Office Coordinator",
      "Office Manager",
      "Front Desk Coordinator",
      "Receptionist",
      "Administrative Coordinator",
      "Program Assistant",
      "Program Coordinator",
      "Project Coordinator",
      "Scheduling Coordinator",
      "Records Coordinator",
      "Data Entry Specialist",
      "Operations Assistant",
      "Department Coordinator",
    ],
    titleBlocklist: ["Intern", "Internship", "Unpaid", "Volunteer"],
    keywordsBoost: [
      "Scheduling",
      "Calendar Management",
      "Customer Service",
      "Data Entry",
      "Records Management",
      "Microsoft Office",
      "Excel",
      "Google Workspace",
      "Phone Support",
      "Email Support",
      "Document Preparation",
      "Office Operations",
      "Meeting Coordination",
      "Travel Coordination",
      "Filing",
      "Vendor Coordination",
      "CRM",
      "Invoicing",
    ],
    keywordsExclude: ["door to door", "commission only", "MLM", "unpaid"],
    locationPreferences: {
      allow_remote: false,
      allow_hybrid: true,
      allow_onsite: true,
    },
    sampleTitles: [
      "Office Manager",
      "Administrative Assistant",
      "Project Coordinator",
    ],
  },
  {
    id: "retail-hospitality",
    name: "Retail & Hospitality",
    description: "Store, food service, guest service, and shift leads",
    icon: "briefcase",
    salaryRange: "$35k - $90k",
    salaryFloor: 35000,
    titleAllowlist: [
      "Retail Associate",
      "Sales Associate",
      "Store Associate",
      "Store Manager",
      "Assistant Store Manager",
      "Shift Lead",
      "Shift Supervisor",
      "Department Manager",
      "Customer Service Representative",
      "Cashier",
      "Guest Service Representative",
      "Front Desk Agent",
      "Hotel Front Desk",
      "Restaurant Manager",
      "Server",
      "Barista",
      "Food Service Worker",
      "Merchandising Associate",
      "Inventory Associate",
      "Team Lead",
    ],
    titleBlocklist: ["Unpaid", "Volunteer", "Commission Only", "Door to Door"],
    keywordsBoost: [
      "Customer Service",
      "Guest Service",
      "Point of Sale",
      "Cash Handling",
      "Inventory",
      "Merchandising",
      "Store Operations",
      "Opening and Closing",
      "Scheduling",
      "Food Safety",
      "Order Fulfillment",
      "BOPIS",
      "Curbside Pickup",
      "Ship From Store",
      "Returns",
      "Team Training",
      "Complaint Resolution",
      "Hospitality",
      "Sales Floor",
      "Stocking",
      "Planograms",
      "Shrink",
      "Loss Prevention",
    ],
    keywordsExclude: ["door to door", "commission only", "MLM", "unpaid"],
    locationPreferences: {
      allow_remote: false,
      allow_hybrid: false,
      allow_onsite: true,
    },
    sampleTitles: ["Store Manager", "Customer Service Rep", "Shift Lead"],
  },
  {
    id: "trades-field-service",
    name: "Trades & Field",
    description: "Technicians, drivers, installers, and field service roles",
    icon: "briefcase",
    salaryRange: "$45k - $110k",
    salaryFloor: 45000,
    titleAllowlist: [
      "Maintenance Technician",
      "Field Service Technician",
      "Service Technician",
      "Installation Technician",
      "HVAC Technician",
      "Electrician",
      "Plumber",
      "Mechanic",
      "Facilities Technician",
      "Equipment Operator",
      "Warehouse Associate",
      "Warehouse Supervisor",
      "Forklift Operator",
      "Delivery Driver",
      "Route Driver",
      "CDL Driver",
      "Dispatcher",
      "Logistics Coordinator",
      "Inventory Coordinator",
      "Parts Specialist",
    ],
    titleBlocklist: [
      "Unpaid",
      "Volunteer",
      "Commission Only",
      "Owner Operator",
    ],
    keywordsBoost: [
      "Equipment Repair",
      "Preventive Maintenance",
      "Work Orders",
      "Troubleshooting",
      "OSHA",
      "Safety Procedures",
      "Hand Tools",
      "Power Tools",
      "Forklift",
      "CDL",
      "Route Planning",
      "Dispatch",
      "Inventory Control",
      "Warehouse Operations",
      "Installation",
      "Customer Service",
      "Facilities",
      "Quality Checks",
    ],
    keywordsExclude: [
      "owner operator",
      "lease purchase",
      "commission only",
      "unpaid",
    ],
    locationPreferences: {
      allow_remote: false,
      allow_hybrid: true,
      allow_onsite: true,
    },
    sampleTitles: [
      "Maintenance Technician",
      "Field Service Tech",
      "Warehouse Supervisor",
    ],
  },
];
