import * as model from "./jobSourceDiscoveryModel";

export const JOB_SOURCE_SPECIALIZED_SECTOR_ENTRIES: readonly model.JobSourceDiscoveryEntry[] = [
  {
    id: "nhs-jobs",
    label: "NHS Jobs",
    category: "healthcare",
    accessModel: "review-required",
    status: "research",
    regions: ["UK"],
    careerProfileIds: model.HEALTHCARE_PROFILE_IDS,
    hostPatterns: ["jobs.nhs.uk"],
    examples: ["UK healthcare jobs"],
    implementationPath:
      "Research official access patterns before adding native support.",
    notes: "High-value healthcare source for UK users.",
  },
  {
    id: "health-ecareers",
    label: "Health eCareers",
    category: "healthcare",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.HEALTHCARE_PROFILE_IDS,
    hostPatterns: ["healthecareers.com"],
    examples: ["Healthcare professional jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Potential healthcare-sector source.",
  },
  {
    id: "practice-match",
    label: "PracticeMatch",
    category: "healthcare",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.HEALTHCARE_PROFILE_IDS,
    hostPatterns: ["practicematch.com"],
    examples: ["Physician and clinician roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Specialized healthcare source.",
  },
  {
    id: "nurse-com",
    label: "Nurse.com",
    category: "healthcare",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.HEALTHCARE_PROFILE_IDS,
    hostPatterns: ["nurse.com"],
    examples: ["Nursing roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Specialized nursing source.",
  },
  {
    id: "vivian-health",
    label: "Vivian Health",
    category: "healthcare",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.HEALTHCARE_PROFILE_IDS,
    hostPatterns: ["vivian.com"],
    examples: ["Healthcare and travel nursing jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "lawjobs",
    label: "Lawjobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.LEGAL_PROFILE_IDS,
    hostPatterns: ["lawjobs.com"],
    examples: ["Legal jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Specialized legal-sector source.",
  },
  {
    id: "idealist",
    label: "Idealist",
    category: "nonprofit",
    accessModel: "review-required",
    status: "research",
    regions: ["US", "global"],
    careerProfileIds: [
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      ...model.EDUCATION_PROFILE_IDS,
      ...model.HEALTHCARE_PROFILE_IDS,
      ...model.LEGAL_PROFILE_IDS,
    ],
    hostPatterns: ["idealist.org"],
    examples: ["Nonprofit jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Important source for nonprofit, education, legal, and operations roles.",
  },
  {
    id: "dribbble",
    label: "Dribbble Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: model.CREATIVE_PROFILE_IDS,
    hostPatterns: ["dribbble.com"],
    examples: ["Design jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Creative and design source.",
  },
  {
    id: "behance",
    label: "Behance Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: model.CREATIVE_PROFILE_IDS,
    hostPatterns: ["behance.net"],
    examples: ["Creative jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Creative and portfolio-adjacent source.",
  },
  {
    id: "aiga-design-jobs",
    label: "AIGA Design Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.CREATIVE_PROFILE_IDS,
    hostPatterns: ["designjobs.aiga.org"],
    examples: ["Design roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Specialized design source.",
  },
  {
    id: "problogger",
    label: "ProBlogger Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: ["content-copywriting", "seo-digital-marketing"],
    hostPatterns: ["problogger.com"],
    examples: ["Writing and content jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Writing and content-marketing source.",
  },
  {
    id: "tech-ladies",
    label: "Tech Ladies",
    category: "sector-specific",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["US", "global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["hiretechladies.com"],
    examples: ["Community technology jobs"],
    implementationPath:
      "Use user-opened import only until community membership and access rules are reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "efinancialcareers",
    label: "eFinancialCareers",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: ["finance-accounting", "data-science"],
    hostPatterns: ["efinancialcareers.com"],
    examples: ["Finance and fintech jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Finance-sector source.",
  },
  {
    id: "accountingfly",
    label: "Accountingfly",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["finance-accounting"],
    hostPatterns: ["accountingfly.com"],
    examples: ["Accounting jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Accounting-sector source.",
  },
  {
    id: "shrm-hr-jobs",
    label: "SHRM HR Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["hr-recruiting"],
    hostPatterns: ["jobs.shrm.org"],
    examples: ["Human resources roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "HR-sector source.",
  },
  {
    id: "ihireconstruction",
    label: "iHireConstruction",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.TRADES_PROFILE_IDS,
    hostPatterns: ["ihireconstruction.com"],
    examples: ["Construction roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Trades and field-service source candidate.",
  },
  {
    id: "bluerecruit",
    label: "BlueRecruit",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.TRADES_PROFILE_IDS,
    hostPatterns: ["bluerecruit.us"],
    examples: ["Skilled trades and blue-collar jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Trades and field-service source candidate.",
  },
  {
    id: "upwork",
    label: "Upwork",
    category: "freelance-contract",
    accessModel: "restricted-user-gated",
    technicalAccess: "authenticated-user-session",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["upwork.com"],
    examples: ["Freelance marketplace jobs"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes:
      "Marketplace terms and account state matter. Do not run silent scheduled discovery.",
    requiresUserAgreement: true,
  },
  {
    id: "freelancer",
    label: "Freelancer",
    category: "freelance-contract",
    accessModel: "restricted-user-gated",
    technicalAccess: "authenticated-user-session",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["freelancer.com"],
    examples: ["Freelance marketplace projects"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes:
      "Marketplace terms and account state matter. Do not run silent scheduled discovery.",
    requiresUserAgreement: true,
  },
  {
    id: "toptal",
    label: "Toptal",
    category: "freelance-contract",
    accessModel: "restricted-user-gated",
    technicalAccess: "authenticated-user-session",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      "software-engineering",
      "data-science",
      "finance-accounting",
      "product-management",
      "creative-media",
    ],
    hostPatterns: ["toptal.com"],
    examples: ["Freelance talent marketplace"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes:
      "Marketplace terms and account state matter. Do not run silent scheduled discovery.",
    requiresUserAgreement: true,
  },
  {
    id: "malt",
    label: "Malt",
    category: "freelance-contract",
    accessModel: "restricted-user-gated",
    technicalAccess: "authenticated-user-session",
    status: "research",
    regions: ["Europe"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["malt.com", "malt.fr", "malt.de"],
    examples: ["European freelance marketplace projects"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes:
      "Marketplace terms and account state matter. Do not run silent scheduled discovery.",
    requiresUserAgreement: true,
  },
  {
    id: "google-jobs-search",
    label: "Google Jobs Search",
    category: "search-engine",
    accessModel: "review-required",
    status: "candidate",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["google.com/search"],
    searchParameterPatterns: [
      "q=<specific-job-search>",
      "ibp=htl;jobs",
      "htivrt=jobs",
    ],
    examples: ["Google job rich results"],
    implementationPath:
      "Candidate user-opened import and visible-result parsing path only; do not run scheduled Google result scraping.",
    notes:
      "Useful for finding employer career pages. Source-mined projects show query-shape and structured-data ideas, but JobSentinel should avoid automated Google search scraping unless a later review proves a permitted path.",
  },
  {
    id: "jobswithgpt",
    label: "JobsWithGPT",
    category: "remote-job-board",
    accessModel: "native-public-feed",
    status: "supported",
    regions: ["global"],
    careerProfileIds: model.TECH_PROFILE_IDS,
    hostPatterns: ["jobswithgpt.com"],
    examples: ["AI and GPT-related roles"],
    implementationPath: "Native JobsWithGPT source.",
    notes:
      "Niche source. Keep it profile-scoped so it does not dominate broader searches.",
  },
] as const;
