import * as model from "./jobSourceDiscoveryModel";
import { JOB_SOURCE_SPECIALIZED_SECTOR_ENTRIES } from "./jobSourceDiscoverySpecializedSectorEntries";

export const JOB_SOURCE_SECTOR_DISCOVERY_ENTRIES: readonly model.JobSourceDiscoveryEntry[] = [
  {
    id: "gov-uk-find-a-job",
    label: "GOV.UK Find a job",
    category: "government-public",
    accessModel: "native-public",
    status: "research",
    regions: ["UK"],
    careerProfileIds: "all",
    hostPatterns: ["findajob.dwp.gov.uk"],
    examples: ["UK public job search"],
    implementationPath:
      "Research official access patterns before adding native support.",
    notes: "Useful for broad UK-market coverage.",
  },
  {
    id: "uk-civil-service-jobs",
    label: "UK Civil Service Jobs",
    category: "government-public",
    accessModel: "review-required",
    status: "research",
    regions: ["UK"],
    careerProfileIds: model.GOVERNMENT_FRIENDLY_PROFILE_IDS,
    hostPatterns: ["civilservicejobs.service.gov.uk"],
    examples: ["UK Civil Service roles"],
    implementationPath:
      "Research official access patterns before adding native support.",
    notes: "Useful for public-sector UK users.",
  },
  {
    id: "adzuna",
    label: "Adzuna",
    category: "broad-job-board",
    accessModel: "native-public-with-local-credential",
    status: "research",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["adzuna.com"],
    examples: ["Adzuna Jobs API"],
    implementationPath:
      "Research API terms, user credential setup, and pricing before native support.",
    notes: "Aggregator API candidate. Keep credentials local and optional.",
  },
  {
    id: "reed",
    label: "Reed",
    category: "broad-job-board",
    accessModel: "native-public-with-local-credential",
    status: "research",
    regions: ["UK"],
    careerProfileIds: "all",
    hostPatterns: ["reed.co.uk"],
    examples: ["Reed UK jobs"],
    implementationPath:
      "Research API terms and local credential flow before native support.",
    notes: "Good UK-market candidate.",
  },
  {
    id: "arbeitnow",
    label: "Arbeitnow",
    category: "international",
    accessModel: "native-public-feed",
    status: "research",
    regions: ["EU"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["arbeitnow.com"],
    examples: ["European job feed"],
    implementationPath:
      "Research feed freshness, terms, and role coverage before native support.",
    notes: "Potential low-friction European source.",
  },
  {
    id: "jooble",
    label: "Jooble",
    category: "broad-job-board",
    accessModel: "native-public-with-local-credential",
    status: "research",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["jooble.org"],
    examples: ["Jooble API"],
    implementationPath:
      "Research API terms, user credential setup, and rate limits before native support.",
    notes: "Aggregator API candidate. Keep credentials local and optional.",
  },
  {
    id: "naukri",
    label: "Naukri",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "candidate",
    regions: ["India"],
    careerProfileIds: "all",
    hostPatterns: ["naukri.com"],
    searchParameterPatterns: [
      "keyword=<role-or-skill>",
      "location=<city-or-state>",
      "remote=true",
      "days=<posted-within-days>",
    ],
    examples: ["India job search"],
    implementationPath:
      "Candidate restricted source after source-specific terms, fixtures, and user-safe errors are reviewed; prefer user-opened import until then.",
    notes:
      "JobSpy shows an account-free web API shape with skills, experience, work-from-home labels, and India salary formats. Do not copy static app tokens, proxy behavior, or broad retry loops.",
    requiresUserAgreement: true,
  },
  {
    id: "foundit",
    label: "Foundit",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["India", "APAC"],
    careerProfileIds: "all",
    hostPatterns: ["foundit.in", "foundit.sg", "foundit.id", "founditgulf.com"],
    examples: ["India and APAC job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "shine",
    label: "Shine",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["India"],
    careerProfileIds: "all",
    hostPatterns: ["shine.com"],
    examples: ["India job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "timesjobs",
    label: "TimesJobs",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["India"],
    careerProfileIds: "all",
    hostPatterns: ["timesjobs.com"],
    examples: ["India job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "seek",
    label: "SEEK",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["Australia", "New Zealand"],
    careerProfileIds: "all",
    hostPatterns: ["seek.com.au", "seek.co.nz"],
    examples: ["Australia and New Zealand job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "jora",
    label: "Jora",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["jora.com"],
    examples: ["International job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "jobstreet",
    label: "JobStreet",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["APAC"],
    careerProfileIds: "all",
    hostPatterns: ["jobstreet.com"],
    examples: ["Southeast Asia job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "bayt",
    label: "Bayt",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "candidate",
    regions: ["Middle East", "North Africa"],
    careerProfileIds: "all",
    hostPatterns: ["bayt.com"],
    searchParameterPatterns: [
      "/en/international/jobs/<query>-jobs/",
      "page=<page-number>",
    ],
    examples: ["MENA job search"],
    implementationPath:
      "Candidate restricted source after source-specific terms, fixtures, and rate limits are reviewed; prefer user-opened import until then.",
    notes:
      "JobSpy demonstrates public HTML parsing for Bayt search pages, but JobSentinel still needs source-specific agreement copy, fixtures, and polite pacing before direct collection.",
    requiresUserAgreement: true,
  },
  {
    id: "bdjobs",
    label: "BDJobs",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "candidate",
    regions: ["Bangladesh"],
    careerProfileIds: "all",
    hostPatterns: ["bdjobs.com", "jobs.bdjobs.com"],
    searchParameterPatterns: [
      "/jobsearch.asp",
      "txtsearch=<role-or-skill>",
      "pg=<page-number>",
    ],
    examples: ["Bangladesh job search"],
    implementationPath:
      "Candidate restricted source after source-specific terms, fixtures, and rate limits are reviewed; prefer user-opened import until then.",
    notes:
      "JobSpy adds a BDJobs parser for Bangladesh coverage. Treat it as source intelligence only until JobSentinel has its own bounded fetch contract, duplicate handling, safe errors, and release proof.",
    requiresUserAgreement: true,
  },
  {
    id: "gulftalent",
    label: "GulfTalent",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["Middle East"],
    careerProfileIds: "all",
    hostPatterns: ["gulftalent.com"],
    examples: ["Gulf region job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "higheredjobs",
    label: "HigherEdJobs",
    category: "higher-education",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: [
      ...model.EDUCATION_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.TECH_PROFILE_IDS,
    ],
    hostPatterns: ["higheredjobs.com"],
    examples: ["Higher education staff, faculty, and administration roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Important education-sector source for campus, staff, faculty, and software roles.",
  },
  {
    id: "chronicle-jobs",
    label: "Chronicle Jobs",
    category: "higher-education",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: [
      ...model.EDUCATION_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.TECH_PROFILE_IDS,
    ],
    hostPatterns: ["jobs.chronicle.com"],
    examples: ["Higher education roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Useful companion source to HigherEdJobs.",
  },
  {
    id: "no-fluff-jobs",
    label: "No Fluff Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["Europe"],
    careerProfileIds: model.TECH_PROFILE_IDS,
    hostPatterns: ["nofluffjobs.com", "nofluffjobs.pl", "nofluffjobs.de"],
    examples: ["Central European technology jobs with strong pay visibility"],
    implementationPath:
      "Review public data shape, salary attribution, and source terms before native support.",
    notes:
      "High-value technology source because pay ranges are prominent, but do not claim native support without fixtures and terms review.",
  },
  {
    id: "justjoinit",
    label: "Just Join IT",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["Europe"],
    careerProfileIds: model.TECH_PROFILE_IDS,
    hostPatterns: ["justjoin.it"],
    examples: ["Central European developer and IT jobs"],
    implementationPath:
      "Review public data shape, salary attribution, and source terms before native support.",
    notes:
      "Useful for European technology roles and pay comparison once source behavior is proven.",
  },
  {
    id: "edjoin",
    label: "EdJoin",
    category: "higher-education",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.EDUCATION_PROFILE_IDS,
    hostPatterns: ["edjoin.org"],
    examples: ["K-12 education jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Useful for K-12 teaching, support, and administrative roles.",
  },
  ...JOB_SOURCE_SPECIALIZED_SECTOR_ENTRIES,
] as const;
