import * as model from "./jobSourceDiscoveryModel";

export const JOB_SOURCE_SPECIALIZED_BOARD_ENTRIES: readonly model.JobSourceDiscoveryEntry[] = [
  {
    id: "remoteok",
    label: "Remote OK",
    category: "remote-job-board",
    accessModel: "native-public-feed",
    status: "supported",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["remoteok.com"],
    examples: ["Remote job feed"],
    implementationPath: "Native Remote OK adapter.",
    notes:
      "Keep remote terms separated from role terms so broad-market roles can use this source.",
  },
  {
    id: "remote-first-jobs",
    label: "Remote First Jobs",
    category: "remote-job-board",
    accessModel: "native-public-feed",
    status: "candidate",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["remotefirstjobs.com", "jobscollider.com"],
    examples: [
      "Remote First Jobs API",
      "Remote First Jobs remote jobs",
      "JobsCollider legacy API",
    ],
    implementationPath:
      "Candidate feed adapter after attribution, freshness, and rate-limit review.",
    notes:
      "Remote-focused public source with explicit source attribution and backlink requirements. JobsCollider API paths now redirect to Remote First Jobs.",
  },
  {
    id: "we-work-remotely",
    label: "We Work Remotely",
    category: "remote-job-board",
    accessModel: "native-public-feed",
    status: "supported",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["weworkremotely.com"],
    examples: ["Remote job categories"],
    implementationPath: "Native We Work Remotely adapter.",
    notes:
      "Strong fit for software, customer success, marketing, sales, and writing roles.",
  },
  {
    id: "remotive",
    label: "Remotive",
    category: "remote-job-board",
    accessModel: "native-public-feed",
    status: "candidate",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["remotive.com"],
    examples: ["Remote jobs API"],
    implementationPath: "Candidate feed adapter after freshness and terms review.",
    notes:
      "Good candidate for non-browser feed discovery if current API behavior remains stable.",
  },
  {
    id: "jobicy",
    label: "Jobicy",
    category: "remote-job-board",
    accessModel: "native-public-feed",
    status: "candidate",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["jobicy.com"],
    examples: ["Remote jobs API", "Remote jobs RSS feeds"],
    implementationPath:
      "Candidate public API/feed adapter after attribution, freshness, and rate-limit review.",
    notes:
      "Remote-focused public source; include required attribution before enabling native results.",
  },
  {
    id: "the-muse",
    label: "The Muse",
    category: "broad-job-board",
    accessModel: "native-public-with-local-credential",
    status: "candidate",
    regions: ["US", "global"],
    careerProfileIds: "all",
    hostPatterns: ["themuse.com"],
    examples: ["The Muse jobs API", "company profile-backed job search"],
    implementationPath:
      "Candidate API adapter only after user-local credential setup, attribution, and quota behavior are implemented.",
    notes:
      "The Muse API can broaden non-technical and company-profile discovery, but credentials and terms must stay local.",
  },
  {
    id: "deel-jobs",
    label: "Deel Jobs",
    category: "remote-job-board",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["deel.com"],
    examples: ["Deel remote and global jobs"],
    implementationPath:
      "Review public job-list behavior before native support; otherwise use user-opened import.",
    notes:
      "Global employment platform jobs can help remote search, but source-specific terms and data shape need review.",
  },
  {
    id: "remote-com-jobs",
    label: "Remote.com Jobs",
    category: "remote-job-board",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["remote.com"],
    examples: ["Remote.com global jobs"],
    implementationPath:
      "Review public job-list behavior before native support; otherwise use user-opened import.",
    notes:
      "Distinct from Remote OK and Remote.co; classify separately so discovery does not merge unrelated sources.",
  },
  {
    id: "remote-co",
    label: "Remote.co",
    category: "remote-job-board",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["remote.co"],
    examples: ["Remote job categories"],
    implementationPath:
      "Research access model. Prefer user-opened import until reviewed.",
    notes: "Good remote discovery candidate, but scheduled access needs review.",
  },
  {
    id: "himalayas",
    label: "Himalayas",
    category: "remote-job-board",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["himalayas.app"],
    examples: ["Remote jobs and companies"],
    implementationPath:
      "Research access model. Prefer user-opened import until reviewed.",
    notes: "Potential remote source and company discovery surface.",
  },
  {
    id: "jobspresso",
    label: "Jobspresso",
    category: "remote-job-board",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["jobspresso.co"],
    examples: ["Remote job listings"],
    implementationPath:
      "Research access model. Prefer user-opened import until reviewed.",
    notes: "Potential curated remote source.",
  },
  {
    id: "working-nomads",
    label: "Working Nomads",
    category: "remote-job-board",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["workingnomads.com"],
    examples: ["Remote job categories"],
    implementationPath:
      "Research access model. Prefer user-opened import until reviewed.",
    notes: "Potential remote source for several broad-market categories.",
  },
  {
    id: "flexjobs",
    label: "FlexJobs",
    category: "remote-job-board",
    accessModel: "restricted-user-gated",
    technicalAccess: "authenticated-user-session",
    status: "restricted",
    regions: ["US", "global"],
    careerProfileIds: "all",
    hostPatterns: ["flexjobs.com"],
    examples: ["Flexible and remote job search"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "usajobs",
    label: "USAJOBS",
    category: "government-public",
    accessModel: "native-public-with-local-credential",
    status: "supported",
    regions: ["US"],
    careerProfileIds: model.GOVERNMENT_FRIENDLY_PROFILE_IDS,
    hostPatterns: ["usajobs.gov", "data.usajobs.gov"],
    examples: ["Federal government jobs"],
    implementationPath: "Native USAJOBS adapter with local API credential setup.",
    notes:
      "Official public source. Keep credential storage local and setup clear for every user.",
  },
  {
    id: "governmentjobs",
    label: "GovernmentJobs",
    category: "public-sector",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.GOVERNMENT_FRIENDLY_PROFILE_IDS,
    hostPatterns: ["governmentjobs.com"],
    examples: ["State, county, city, and public agency jobs"],
    implementationPath:
      "Research public access model and jurisdiction-specific pages before automation.",
    notes:
      "High-value public-sector source, especially for broad-market job seekers.",
  },
  {
    id: "clearancejobs",
    label: "ClearanceJobs",
    category: "sector-specific",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["US"],
    careerProfileIds: [
      "cybersecurity",
      "software-engineering",
      "trades-field-service",
      "project-operations",
    ],
    hostPatterns: ["clearancejobs.com"],
    examples: ["Security clearance roles"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "snagajob",
    label: "Snagajob",
    category: "sector-specific",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["retail-hospitality"],
    hostPatterns: ["snagajob.com"],
    examples: ["Hourly retail, restaurant, and hospitality jobs"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "poached-jobs",
    label: "Poached Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["retail-hospitality"],
    hostPatterns: ["poachedjobs.com"],
    examples: ["Restaurant and hospitality jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Hospitality-specific source for local market coverage.",
  },
  {
    id: "culinary-agents",
    label: "Culinary Agents",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["retail-hospitality"],
    hostPatterns: ["culinaryagents.com"],
    examples: ["Restaurant, hotel, and culinary roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Hospitality-specific source for local market coverage.",
  },
  {
    id: "hospitality-online",
    label: "Hospitality Online",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["retail-hospitality"],
    hostPatterns: ["hospitalityonline.com"],
    examples: ["Hotel and hospitality jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Hospitality-specific source for hotel and service roles.",
  },
  {
    id: "coolworks",
    label: "CoolWorks",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["retail-hospitality", "trades-field-service"],
    hostPatterns: ["coolworks.com"],
    examples: ["Seasonal, outdoor, hospitality, and park jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes:
      "Useful for seasonal hospitality, field, parks, and entry-level local roles.",
  },
  {
    id: "eures",
    label: "EURES",
    category: "government-public",
    accessModel: "native-public",
    status: "research",
    regions: ["EU"],
    careerProfileIds: "all",
    hostPatterns: ["eures.europa.eu"],
    examples: ["European public employment services"],
    implementationPath:
      "Research official API and country coverage before adding native support.",
    notes: "Good official international source candidate.",
  },
  {
    id: "canada-job-bank",
    label: "Canada Job Bank",
    category: "government-public",
    accessModel: "native-public",
    status: "research",
    regions: ["Canada"],
    careerProfileIds: "all",
    hostPatterns: ["jobbank.gc.ca"],
    examples: ["Government of Canada Job Bank"],
    implementationPath:
      "Research official feeds or API terms before adding native support.",
    notes: "Good public-source candidate for Canadian job seekers.",
  },
] as const;
