import * as model from "./jobSourceDiscoveryModel";

export const JOB_SOURCE_SECTOR_DISCOVERY_ENTRIES: readonly model.JobSourceDiscoveryEntry[] = [
  {
    id: "gov-uk-find-a-job",
    label: "GOV.UK Find a job",
    category: "government-public",
    accessModel: "native-public",
    status: "research",
    regions: ["UK"],
    careerProfileIds: "all",
    hostPatterns: ["findajob.dwp.gov.uk"],
    examples: ["UK public job search"],
    implementationPath:
      "Research official access patterns before adding native support.",
    notes: "Useful for broad UK-market coverage.",
  },
  {
    id: "uk-civil-service-jobs",
    label: "UK Civil Service Jobs",
    category: "government-public",
    accessModel: "review-required",
    status: "research",
    regions: ["UK"],
    careerProfileIds: model.GOVERNMENT_FRIENDLY_PROFILE_IDS,
    hostPatterns: ["civilservicejobs.service.gov.uk"],
    examples: ["UK Civil Service roles"],
    implementationPath:
      "Research official access patterns before adding native support.",
    notes: "Useful for public-sector UK users.",
  },
  {
    id: "adzuna",
    label: "Adzuna",
    category: "broad-job-board",
    accessModel: "native-public-with-local-credential",
    status: "research",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["adzuna.com"],
    examples: ["Adzuna Jobs API"],
    implementationPath:
      "Research API terms, user credential setup, and pricing before native support.",
    notes: "Aggregator API candidate. Keep credentials local and optional.",
  },
  {
    id: "reed",
    label: "Reed",
    category: "broad-job-board",
    accessModel: "native-public-with-local-credential",
    status: "research",
    regions: ["UK"],
    careerProfileIds: "all",
    hostPatterns: ["reed.co.uk"],
    examples: ["Reed UK jobs"],
    implementationPath:
      "Research API terms and local credential flow before native support.",
    notes: "Good UK-market candidate.",
  },
  {
    id: "arbeitnow",
    label: "Arbeitnow",
    category: "international",
    accessModel: "native-public-feed",
    status: "research",
    regions: ["EU"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["arbeitnow.com"],
    examples: ["European job feed"],
    implementationPath:
      "Research feed freshness, terms, and role coverage before native support.",
    notes: "Potential low-friction European source.",
  },
  {
    id: "jooble",
    label: "Jooble",
    category: "broad-job-board",
    accessModel: "native-public-with-local-credential",
    status: "research",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["jooble.org"],
    examples: ["Jooble API"],
    implementationPath:
      "Research API terms, user credential setup, and rate limits before native support.",
    notes: "Aggregator API candidate. Keep credentials local and optional.",
  },
  {
    id: "naukri",
    label: "Naukri",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["India"],
    careerProfileIds: "all",
    hostPatterns: ["naukri.com"],
    examples: ["India job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "foundit",
    label: "Foundit",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["India", "APAC"],
    careerProfileIds: "all",
    hostPatterns: ["foundit.in", "foundit.sg", "foundit.id", "founditgulf.com"],
    examples: ["India and APAC job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "shine",
    label: "Shine",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["India"],
    careerProfileIds: "all",
    hostPatterns: ["shine.com"],
    examples: ["India job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "timesjobs",
    label: "TimesJobs",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["India"],
    careerProfileIds: "all",
    hostPatterns: ["timesjobs.com"],
    examples: ["India job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "seek",
    label: "SEEK",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["Australia", "New Zealand"],
    careerProfileIds: "all",
    hostPatterns: ["seek.com.au", "seek.co.nz"],
    examples: ["Australia and New Zealand job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "jora",
    label: "Jora",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["jora.com"],
    examples: ["International job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "jobstreet",
    label: "JobStreet",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["APAC"],
    careerProfileIds: "all",
    hostPatterns: ["jobstreet.com"],
    examples: ["Southeast Asia job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "bayt",
    label: "Bayt",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["Middle East", "North Africa"],
    careerProfileIds: "all",
    hostPatterns: ["bayt.com"],
    examples: ["MENA job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "gulftalent",
    label: "GulfTalent",
    category: "international",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["Middle East"],
    careerProfileIds: "all",
    hostPatterns: ["gulftalent.com"],
    examples: ["Gulf region job search"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "higheredjobs",
    label: "HigherEdJobs",
    category: "higher-education",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: [
      ...model.EDUCATION_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.TECH_PROFILE_IDS,
    ],
    hostPatterns: ["higheredjobs.com"],
    examples: ["Higher education staff, faculty, and administration roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Important education-sector source for campus, staff, faculty, and software roles.",
  },
  {
    id: "chronicle-jobs",
    label: "Chronicle Jobs",
    category: "higher-education",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: [
      ...model.EDUCATION_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.TECH_PROFILE_IDS,
    ],
    hostPatterns: ["jobs.chronicle.com"],
    examples: ["Higher education roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Useful companion source to HigherEdJobs.",
  },
  {
    id: "no-fluff-jobs",
    label: "No Fluff Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["Europe"],
    careerProfileIds: model.TECH_PROFILE_IDS,
    hostPatterns: ["nofluffjobs.com", "nofluffjobs.pl", "nofluffjobs.de"],
    examples: ["Central European technology jobs with strong pay visibility"],
    implementationPath:
      "Review public data shape, salary attribution, and source terms before native support.",
    notes:
      "High-value technology source because pay ranges are prominent, but do not claim native support without fixtures and terms review.",
  },
  {
    id: "justjoinit",
    label: "Just Join IT",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["Europe"],
    careerProfileIds: model.TECH_PROFILE_IDS,
    hostPatterns: ["justjoin.it"],
    examples: ["Central European developer and IT jobs"],
    implementationPath:
      "Review public data shape, salary attribution, and source terms before native support.",
    notes:
      "Useful for European technology roles and pay comparison once source behavior is proven.",
  },
  {
    id: "edjoin",
    label: "EdJoin",
    category: "higher-education",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.EDUCATION_PROFILE_IDS,
    hostPatterns: ["edjoin.org"],
    examples: ["K-12 education jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Useful for K-12 teaching, support, and administrative roles.",
  },
  {
    id: "nhs-jobs",
    label: "NHS Jobs",
    category: "healthcare",
    accessModel: "review-required",
    status: "research",
    regions: ["UK"],
    careerProfileIds: model.HEALTHCARE_PROFILE_IDS,
    hostPatterns: ["jobs.nhs.uk"],
    examples: ["UK healthcare jobs"],
    implementationPath:
      "Research official access patterns before adding native support.",
    notes: "High-value healthcare source for UK users.",
  },
  {
    id: "health-ecareers",
    label: "Health eCareers",
    category: "healthcare",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.HEALTHCARE_PROFILE_IDS,
    hostPatterns: ["healthecareers.com"],
    examples: ["Healthcare professional jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Potential healthcare-sector source.",
  },
  {
    id: "practice-match",
    label: "PracticeMatch",
    category: "healthcare",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.HEALTHCARE_PROFILE_IDS,
    hostPatterns: ["practicematch.com"],
    examples: ["Physician and clinician roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Specialized healthcare source.",
  },
  {
    id: "nurse-com",
    label: "Nurse.com",
    category: "healthcare",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.HEALTHCARE_PROFILE_IDS,
    hostPatterns: ["nurse.com"],
    examples: ["Nursing roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Specialized nursing source.",
  },
  {
    id: "vivian-health",
    label: "Vivian Health",
    category: "healthcare",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.HEALTHCARE_PROFILE_IDS,
    hostPatterns: ["vivian.com"],
    examples: ["Healthcare and travel nursing jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "lawjobs",
    label: "Lawjobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.LEGAL_PROFILE_IDS,
    hostPatterns: ["lawjobs.com"],
    examples: ["Legal jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Specialized legal-sector source.",
  },
  {
    id: "idealist",
    label: "Idealist",
    category: "nonprofit",
    accessModel: "review-required",
    status: "research",
    regions: ["US", "global"],
    careerProfileIds: [
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      ...model.EDUCATION_PROFILE_IDS,
      ...model.HEALTHCARE_PROFILE_IDS,
      ...model.LEGAL_PROFILE_IDS,
    ],
    hostPatterns: ["idealist.org"],
    examples: ["Nonprofit jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Important source for nonprofit, education, legal, and operations roles.",
  },
  {
    id: "dribbble",
    label: "Dribbble Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: model.CREATIVE_PROFILE_IDS,
    hostPatterns: ["dribbble.com"],
    examples: ["Design jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Creative and design source.",
  },
  {
    id: "behance",
    label: "Behance Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: model.CREATIVE_PROFILE_IDS,
    hostPatterns: ["behance.net"],
    examples: ["Creative jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Creative and portfolio-adjacent source.",
  },
  {
    id: "aiga-design-jobs",
    label: "AIGA Design Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.CREATIVE_PROFILE_IDS,
    hostPatterns: ["designjobs.aiga.org"],
    examples: ["Design roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Specialized design source.",
  },
  {
    id: "problogger",
    label: "ProBlogger Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: ["content-copywriting", "seo-digital-marketing"],
    hostPatterns: ["problogger.com"],
    examples: ["Writing and content jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Writing and content-marketing source.",
  },
  {
    id: "tech-ladies",
    label: "Tech Ladies",
    category: "sector-specific",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["US", "global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["hiretechladies.com"],
    examples: ["Community technology jobs"],
    implementationPath:
      "Use user-opened import only until community membership and access rules are reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "efinancialcareers",
    label: "eFinancialCareers",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: ["finance-accounting", "data-science"],
    hostPatterns: ["efinancialcareers.com"],
    examples: ["Finance and fintech jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Finance-sector source.",
  },
  {
    id: "accountingfly",
    label: "Accountingfly",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["finance-accounting"],
    hostPatterns: ["accountingfly.com"],
    examples: ["Accounting jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Accounting-sector source.",
  },
  {
    id: "shrm-hr-jobs",
    label: "SHRM HR Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["hr-recruiting"],
    hostPatterns: ["jobs.shrm.org"],
    examples: ["Human resources roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "HR-sector source.",
  },
  {
    id: "ihireconstruction",
    label: "iHireConstruction",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.TRADES_PROFILE_IDS,
    hostPatterns: ["ihireconstruction.com"],
    examples: ["Construction roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Trades and field-service source candidate.",
  },
  {
    id: "bluerecruit",
    label: "BlueRecruit",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.TRADES_PROFILE_IDS,
    hostPatterns: ["bluerecruit.us"],
    examples: ["Skilled trades and blue-collar jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Trades and field-service source candidate.",
  },
  {
    id: "upwork",
    label: "Upwork",
    category: "freelance-contract",
    accessModel: "restricted-user-gated",
    technicalAccess: "authenticated-user-session",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["upwork.com"],
    examples: ["Freelance marketplace jobs"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes:
      "Marketplace terms and account state matter. Do not run silent scheduled discovery.",
    requiresUserAgreement: true,
  },
  {
    id: "freelancer",
    label: "Freelancer",
    category: "freelance-contract",
    accessModel: "restricted-user-gated",
    technicalAccess: "authenticated-user-session",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["freelancer.com"],
    examples: ["Freelance marketplace projects"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes:
      "Marketplace terms and account state matter. Do not run silent scheduled discovery.",
    requiresUserAgreement: true,
  },
  {
    id: "toptal",
    label: "Toptal",
    category: "freelance-contract",
    accessModel: "restricted-user-gated",
    technicalAccess: "authenticated-user-session",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      "software-engineering",
      "data-science",
      "finance-accounting",
      "product-management",
      "creative-media",
    ],
    hostPatterns: ["toptal.com"],
    examples: ["Freelance talent marketplace"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes:
      "Marketplace terms and account state matter. Do not run silent scheduled discovery.",
    requiresUserAgreement: true,
  },
  {
    id: "malt",
    label: "Malt",
    category: "freelance-contract",
    accessModel: "restricted-user-gated",
    technicalAccess: "authenticated-user-session",
    status: "research",
    regions: ["Europe"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["malt.com", "malt.fr", "malt.de"],
    examples: ["European freelance marketplace projects"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes:
      "Marketplace terms and account state matter. Do not run silent scheduled discovery.",
    requiresUserAgreement: true,
  },
  {
    id: "google-jobs-search",
    label: "Google Jobs Search",
    category: "search-engine",
    accessModel: "review-required",
    status: "manual-only",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["google.com/search"],
    examples: ["Google job rich results"],
    implementationPath:
      "Use as a manual discovery aid or user-opened import path, not scheduled scraping.",
    notes:
      "Useful for finding employer career pages, but direct automated search scraping should stay disabled.",
  },
  {
    id: "jobswithgpt",
    label: "JobsWithGPT",
    category: "remote-job-board",
    accessModel: "native-public-feed",
    status: "supported",
    regions: ["global"],
    careerProfileIds: model.TECH_PROFILE_IDS,
    hostPatterns: ["jobswithgpt.com"],
    examples: ["AI and GPT-related roles"],
    implementationPath: "Native JobsWithGPT source.",
    notes:
      "Niche source. Keep it profile-scoped so it does not dominate broader searches.",
  },
] as const;
