import * as model from "./jobSourceDiscoveryModel";

export const JOB_SOURCE_BOARDS_DISCOVERY_ENTRIES: readonly model.JobSourceDiscoveryEntry[] = [
  {
    id: "indeed",
    label: "Indeed",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["indeed.com"],
    examples: ["Indeed job search results"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "monster",
    label: "Monster",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["US", "global"],
    careerProfileIds: "all",
    hostPatterns: ["monster.com"],
    examples: ["Monster job search"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "ziprecruiter",
    label: "ZipRecruiter",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["US"],
    careerProfileIds: "all",
    hostPatterns: ["ziprecruiter.com"],
    examples: ["ZipRecruiter search results"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "careerbuilder",
    label: "CareerBuilder",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["US"],
    careerProfileIds: "all",
    hostPatterns: ["careerbuilder.com"],
    examples: ["CareerBuilder search results"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "glassdoor",
    label: "Glassdoor",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["glassdoor.com"],
    examples: ["Glassdoor job search"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "simplyhired",
    label: "SimplyHired",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["US"],
    careerProfileIds: "all",
    hostPatterns: ["simplyhired.com"],
    examples: ["SimplyHired search results"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "builtin",
    label: "Built In",
    category: "regional-local",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["US"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["builtin.com", "builtincolorado.com"],
    locationSearchPatterns: [
      "/jobs",
      "/jobs?state=<state>&country=<country>&allLocations=true",
      "/jobs?city=<city>&state=<state>&country=<country>&allLocations=true",
      "regional city hosts such as builtincolorado.com/jobs",
    ],
    examples: [
      "Built In network jobs",
      "Built In California",
      "Built In San Francisco",
      "Built In Colorado",
      "Built In NYC",
      "Built In Chicago",
    ],
    implementationPath:
      "Use employer discovery from listings and explicit user-gated access only for board scraping.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "regional-industry-boards",
    label: "Regional Industry Boards",
    category: "regional-local",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["US", "global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["builtin*.com", "local industry council job boards"],
    examples: [
      "Built In Colorado",
      "local industry council job boards",
      "regional startup community job boards",
    ],
    implementationPath:
      "Treat regional boards as source-discovery candidates. Prefer employer-career follow-through and require explicit user agreement before board automation.",
    notes:
      "Regional sites are high-value for location-bound users, but access models vary by city and operator.",
    requiresUserAgreement: true,
  },
  {
    id: "state-workforce-boards",
    label: "State Workforce Boards",
    category: "regional-local",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: "all",
    hostPatterns: [
      "state workforce job banks",
      "state labor department job boards",
    ],
    examples: [
      "state workforce center jobs",
      "state department of labor job banks",
      "American Job Center-linked listings",
    ],
    implementationPath:
      "Research each jurisdiction. Prefer official feeds where available, otherwise offer user-opened search links and manual import.",
    notes:
      "Important for local, frontline, government-adjacent, and broad-market roles that may not appear on national boards.",
  },
  {
    id: "city-county-careers",
    label: "City and County Careers",
    category: "public-sector",
    accessModel: "employer-career-system",
    status: "research",
    regions: ["global"],
    careerProfileIds: model.GOVERNMENT_FRIENDLY_PROFILE_IDS,
    hostPatterns: [
      "city career pages",
      "county career pages",
      "municipal applicant portals",
    ],
    examples: [
      "city government careers",
      "county government jobs",
      "public utility career pages",
    ],
    implementationPath:
      "Detect ATS platform first. If no stable public endpoint exists, use user-opened search, pasted job links, or manual entry.",
    notes:
      "Many local public employers use vendor portals or custom pages; model them as employer-career discovery instead of broad scraping.",
  },
  {
    id: "local-chambers-economic-development",
    label: "Local Chambers and Economic Development Boards",
    category: "regional-local",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: [
      "chamber job boards",
      "economic development job boards",
      "regional business association job boards",
    ],
    examples: [
      "local chamber of commerce job boards",
      "regional economic development job boards",
      "industry association local listings",
    ],
    implementationPath:
      "Use as a discovery path for local employers. Add native source support only after source-specific terms and structure review.",
    notes:
      "Useful for retail, hospitality, operations, trades, office, and small-business roles.",
  },
  {
    id: "local-newspaper-jobs",
    label: "Local Newspaper Jobs",
    category: "regional-local",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["local newspaper job boards", "regional classifieds jobs"],
    examples: ["regional newspaper job boards", "local classified job pages"],
    implementationPath:
      "Use user-opened search and manual import until source-specific rights and structure are reviewed.",
    notes:
      "Can surface local roles missed by national boards, but source behavior varies widely.",
  },
  {
    id: "dice",
    label: "Dice",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["US"],
    careerProfileIds: model.TECH_PROFILE_IDS,
    hostPatterns: ["dice.com"],
    examples: ["Technology job search"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "wellfound",
    label: "Wellfound",
    category: "startup-job-board",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["wellfound.com"],
    examples: ["Startup hiring"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "yc-work-at-a-startup",
    label: "Y Combinator Work at a Startup",
    category: "startup-job-board",
    accessModel: "native-public",
    status: "supported",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["ycombinator.com/companies/jobs"],
    examples: ["YC startup jobs"],
    implementationPath: "Native YC adapter.",
    notes:
      "Useful for startup discovery and direct company career-page expansion.",
  },
  {
    id: "hacker-news-who-is-hiring",
    label: "Hacker News Who Is Hiring",
    category: "public-community",
    accessModel: "public-community",
    status: "supported",
    regions: ["global"],
    careerProfileIds: model.TECH_PROFILE_IDS,
    hostPatterns: ["news.ycombinator.com/item"],
    examples: ["Monthly Who Is Hiring thread"],
    implementationPath: "Native Hacker News source.",
    notes:
      "Community postings need quality and risk scoring because detail levels vary.",
  },
  {
    id: "remoteok",
    label: "Remote OK",
    category: "remote-job-board",
    accessModel: "native-public-feed",
    status: "supported",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["remoteok.com"],
    examples: ["Remote job feed"],
    implementationPath: "Native Remote OK adapter.",
    notes:
      "Keep remote terms separated from role terms so broad-market roles can use this source.",
  },
  {
    id: "we-work-remotely",
    label: "We Work Remotely",
    category: "remote-job-board",
    accessModel: "native-public-feed",
    status: "supported",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["weworkremotely.com"],
    examples: ["Remote job categories"],
    implementationPath: "Native We Work Remotely adapter.",
    notes:
      "Strong fit for software, customer success, marketing, sales, and writing roles.",
  },
  {
    id: "remotive",
    label: "Remotive",
    category: "remote-job-board",
    accessModel: "native-public-feed",
    status: "candidate",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["remotive.com"],
    examples: ["Remote jobs API"],
    implementationPath: "Candidate feed adapter after freshness and terms review.",
    notes:
      "Good candidate for non-browser feed discovery if current API behavior remains stable.",
  },
  {
    id: "remote-co",
    label: "Remote.co",
    category: "remote-job-board",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["remote.co"],
    examples: ["Remote job categories"],
    implementationPath:
      "Research access model. Prefer user-opened import until reviewed.",
    notes: "Good remote discovery candidate, but scheduled access needs review.",
  },
  {
    id: "himalayas",
    label: "Himalayas",
    category: "remote-job-board",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["himalayas.app"],
    examples: ["Remote jobs and companies"],
    implementationPath:
      "Research access model. Prefer user-opened import until reviewed.",
    notes: "Potential remote source and company discovery surface.",
  },
  {
    id: "jobspresso",
    label: "Jobspresso",
    category: "remote-job-board",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["jobspresso.co"],
    examples: ["Remote job listings"],
    implementationPath:
      "Research access model. Prefer user-opened import until reviewed.",
    notes: "Potential curated remote source.",
  },
  {
    id: "working-nomads",
    label: "Working Nomads",
    category: "remote-job-board",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["workingnomads.com"],
    examples: ["Remote job categories"],
    implementationPath:
      "Research access model. Prefer user-opened import until reviewed.",
    notes: "Potential remote source for several broad-market categories.",
  },
  {
    id: "flexjobs",
    label: "FlexJobs",
    category: "remote-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["US", "global"],
    careerProfileIds: "all",
    hostPatterns: ["flexjobs.com"],
    examples: ["Flexible and remote job search"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "usajobs",
    label: "USAJOBS",
    category: "government-public",
    accessModel: "native-public-with-local-credential",
    status: "supported",
    regions: ["US"],
    careerProfileIds: model.GOVERNMENT_FRIENDLY_PROFILE_IDS,
    hostPatterns: ["usajobs.gov", "data.usajobs.gov"],
    examples: ["Federal government jobs"],
    implementationPath: "Native USAJOBS adapter with local API credential setup.",
    notes:
      "Official public source. Keep credential storage local and setup clear for every user.",
  },
  {
    id: "governmentjobs",
    label: "GovernmentJobs",
    category: "public-sector",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: model.GOVERNMENT_FRIENDLY_PROFILE_IDS,
    hostPatterns: ["governmentjobs.com"],
    examples: ["State, county, city, and public agency jobs"],
    implementationPath:
      "Research public access model and jurisdiction-specific pages before automation.",
    notes:
      "High-value public-sector source, especially for broad-market job seekers.",
  },
  {
    id: "clearancejobs",
    label: "ClearanceJobs",
    category: "sector-specific",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["US"],
    careerProfileIds: [
      "cybersecurity",
      "software-engineering",
      "trades-field-service",
      "project-operations",
    ],
    hostPatterns: ["clearancejobs.com"],
    examples: ["Security clearance roles"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "snagajob",
    label: "Snagajob",
    category: "sector-specific",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["retail-hospitality"],
    hostPatterns: ["snagajob.com"],
    examples: ["Hourly retail, restaurant, and hospitality jobs"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "poached-jobs",
    label: "Poached Jobs",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["retail-hospitality"],
    hostPatterns: ["poachedjobs.com"],
    examples: ["Restaurant and hospitality jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Hospitality-specific source for local market coverage.",
  },
  {
    id: "culinary-agents",
    label: "Culinary Agents",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["retail-hospitality"],
    hostPatterns: ["culinaryagents.com"],
    examples: ["Restaurant, hotel, and culinary roles"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Hospitality-specific source for local market coverage.",
  },
  {
    id: "hospitality-online",
    label: "Hospitality Online",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["retail-hospitality"],
    hostPatterns: ["hospitalityonline.com"],
    examples: ["Hotel and hospitality jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: "Hospitality-specific source for hotel and service roles.",
  },
  {
    id: "coolworks",
    label: "CoolWorks",
    category: "sector-specific",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: ["retail-hospitality", "trades-field-service"],
    hostPatterns: ["coolworks.com"],
    examples: ["Seasonal, outdoor, hospitality, and park jobs"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes:
      "Useful for seasonal hospitality, field, parks, and entry-level local roles.",
  },
  {
    id: "eures",
    label: "EURES",
    category: "government-public",
    accessModel: "native-public",
    status: "research",
    regions: ["EU"],
    careerProfileIds: "all",
    hostPatterns: ["eures.europa.eu"],
    examples: ["European public employment services"],
    implementationPath:
      "Research official API and country coverage before adding native support.",
    notes: "Good official international source candidate.",
  },
  {
    id: "canada-job-bank",
    label: "Canada Job Bank",
    category: "government-public",
    accessModel: "native-public",
    status: "research",
    regions: ["Canada"],
    careerProfileIds: "all",
    hostPatterns: ["jobbank.gc.ca"],
    examples: ["Government of Canada Job Bank"],
    implementationPath:
      "Research official feeds or API terms before adding native support.",
    notes: "Good public-source candidate for Canadian job seekers.",
  },
] as const;
