display_information:
  name: Personal Job Finder
  description: Sends you alerts when jobs matching your preferences are found.
  background_color: "#2f3136"
features:
  bot_user:
    display_name: Job Finder Bot
    always_online: false
  slash_commands:
    - command: /jobfinder
      url: https://example.com/slack/commands # This URL is required but not used by our app
      description: Commands for your Job Finder.
      should_escape: false
oauth_config:
  scopes:
    bot:
      - incoming-webhook
settings:
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
