export interface CompanyInfo {
  name: string;
  description?: string;
  industry?: string;
  founded?: string;
  headquarters?: string;
  employeeCount?: string;
  website?: string;
  linkedinUrl?: string;
  glassdoorRating?: number;
  // Funding info (for startups)
  fundingStage?: string;
  totalFunding?: string;
  // Culture and role signals
  remotePolicy?: string;
  toolsAndSystems?: string[];
  // Legacy cache field kept so old local profile cache entries still render.
  techStack?: string[];
}

// Well-known companies database (local fallback when live lookup is unavailable)
export const KNOWN_COMPANIES: Record<string, Partial<CompanyInfo>> = {
  // Healthcare and care delivery
  'kaiser': {
    industry: 'Healthcare / Care Delivery',
    employeeCount: 'Large employer',
    website: 'https://www.kaiserpermanente.org',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Patient scheduling', 'Electronic health records', 'Care coordination', 'Member services'],
  },
  'mayo': {
    industry: 'Healthcare / Research',
    employeeCount: 'Large employer',
    website: 'https://www.mayoclinic.org',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Patient care', 'Clinical research', 'Scheduling', 'Care coordination'],
  },
  'cvs': {
    industry: 'Healthcare / Retail',
    employeeCount: 'Large employer',
    website: 'https://www.cvshealth.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Pharmacy systems', 'Customer service', 'Inventory', 'Benefits coordination'],
  },
  'cleveland clinic': {
    industry: 'Healthcare / Care Delivery',
    employeeCount: 'Large employer',
    website: 'https://my.clevelandclinic.org',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Patient care', 'Scheduling', 'Care coordination', 'Clinical operations'],
  },
  'hca healthcare': {
    industry: 'Healthcare / Hospital Operations',
    employeeCount: 'Large employer',
    website: 'https://hcahealthcare.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Patient registration', 'Clinical support', 'Case management', 'Hospital operations'],
  },
  'unitedhealth group': {
    industry: 'Healthcare / Insurance',
    employeeCount: 'Large employer',
    website: 'https://www.unitedhealthgroup.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Member services', 'Claims support', 'Care coordination', 'Benefits operations'],
  },
  // Retail, service, and trades
  'walmart': {
    industry: 'Retail / Operations',
    employeeCount: 'Large employer',
    website: 'https://www.walmart.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Store operations', 'Inventory', 'Customer service', 'Supply chain'],
  },
  'target': {
    industry: 'Retail',
    employeeCount: 'Large employer',
    website: 'https://www.target.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Guest service', 'Merchandising', 'Inventory', 'Fulfillment'],
  },
  'home depot': {
    industry: 'Retail / Trades',
    employeeCount: 'Large employer',
    website: 'https://www.homedepot.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Customer projects', 'Merchandising', 'Inventory', 'Pro desk support'],
  },
  'starbucks': {
    industry: 'Food Service / Retail',
    employeeCount: 'Large employer',
    website: 'https://www.starbucks.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Guest service', 'Scheduling', 'Store operations', 'Training'],
  },
  'costco': {
    industry: 'Retail / Warehouse',
    employeeCount: 'Large employer',
    website: 'https://www.costco.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Member service', 'Warehouse operations', 'Inventory', 'Merchandising'],
  },
  'lowes': {
    industry: 'Retail / Home Improvement',
    employeeCount: 'Large employer',
    website: 'https://www.lowes.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Customer projects', 'Store operations', 'Inventory', 'Pro services'],
  },
  'mcdonalds': {
    industry: 'Food Service',
    employeeCount: 'Large employer',
    website: 'https://www.mcdonalds.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Guest service', 'Store operations', 'Training', 'Scheduling'],
  },
  // Logistics, hospitality, finance, and public service
  'ups': {
    industry: 'Logistics',
    employeeCount: 'Large employer',
    website: 'https://www.ups.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Route planning', 'Package handling', 'Dispatch', 'Customer support'],
  },
  'marriott': {
    industry: 'Hospitality',
    employeeCount: 'Large employer',
    website: 'https://www.marriott.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Guest service', 'Reservations', 'Event support', 'Property operations'],
  },
  'fedex': {
    industry: 'Logistics',
    employeeCount: 'Large employer',
    website: 'https://www.fedex.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Package handling', 'Dispatch', 'Route planning', 'Customer support'],
  },
  'southwest airlines': {
    industry: 'Airlines / Travel',
    employeeCount: 'Large employer',
    website: 'https://www.southwest.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Guest service', 'Reservations', 'Airport operations', 'Scheduling'],
  },
  'hilton': {
    industry: 'Hospitality',
    employeeCount: 'Large employer',
    website: 'https://www.hilton.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Guest service', 'Reservations', 'Property operations', 'Event support'],
  },
  'state farm': {
    industry: 'Insurance',
    employeeCount: 'Large employer',
    website: 'https://www.statefarm.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Claims support', 'Customer service', 'Policy servicing', 'Sales support'],
  },
  'bank of america': {
    industry: 'Banking / Financial Services',
    employeeCount: 'Large employer',
    website: 'https://www.bankofamerica.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Customer accounts', 'Financial services', 'Risk controls', 'Branch operations'],
  },
  'city of phoenix': {
    industry: 'Government / Public Service',
    employeeCount: 'Public employer',
    website: 'https://www.phoenix.gov',
    remotePolicy: 'Varies by department',
    toolsAndSystems: ['Public service', 'Case tracking', 'Community programs', 'Resident support'],
  },
  'usps': {
    industry: 'Government / Postal Service',
    employeeCount: 'Public employer',
    website: 'https://www.usps.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Mail handling', 'Route operations', 'Customer service', 'Distribution'],
  },
  'denver public schools': {
    industry: 'Education / Public Service',
    employeeCount: 'Public employer',
    website: 'https://www.dpsk12.org',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Student support', 'School operations', 'Family services', 'Program coordination'],
  },
  'progressive': {
    industry: 'Insurance',
    employeeCount: 'Large employer',
    website: 'https://www.progressive.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Claims support', 'Customer service', 'Policy servicing', 'Sales support'],
  },
  // Large technology and online service employers
  'google': {
    industry: 'Technology',
    founded: '1998',
    headquarters: 'Mountain View, CA',
    employeeCount: '180,000+',
    website: 'https://google.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Search operations', 'Advertising tools', 'Customer support', 'Data reporting', 'Program coordination'],
  },
  'meta': {
    industry: 'Technology / Social Media',
    founded: '2004',
    headquarters: 'Menlo Park, CA',
    employeeCount: '67,000+',
    website: 'https://meta.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Content operations', 'Community support', 'Advertising tools', 'Trust and safety', 'Partner support'],
  },
  'amazon': {
    industry: 'Technology / E-commerce',
    founded: '1994',
    headquarters: 'Seattle, WA',
    employeeCount: '1,500,000+',
    website: 'https://amazon.com',
    remotePolicy: 'Varies by team',
    toolsAndSystems: ['Fulfillment operations', 'Seller support', 'Inventory systems', 'Customer service', 'Workforce scheduling'],
  },
  'microsoft': {
    industry: 'Technology',
    founded: '1975',
    headquarters: 'Redmond, WA',
    employeeCount: '220,000+',
    website: 'https://microsoft.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer success', 'Business applications', 'Support operations', 'Partner programs', 'Documentation'],
  },
  'apple': {
    industry: 'Technology / Consumer Electronics',
    founded: '1976',
    headquarters: 'Cupertino, CA',
    employeeCount: '160,000+',
    website: 'https://apple.com',
    remotePolicy: 'Mostly On-site',
    toolsAndSystems: ['Retail operations', 'Customer support', 'Product support', 'Inventory systems', 'Training'],
  },
  'netflix': {
    industry: 'Entertainment / Streaming',
    founded: '1997',
    headquarters: 'Los Gatos, CA',
    employeeCount: '13,000+',
    website: 'https://netflix.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Content operations', 'Member support', 'Production coordination', 'Localization', 'Partner support'],
  },
  // AI Companies
  'openai': {
    industry: 'AI / Research',
    founded: '2015',
    headquarters: 'San Francisco, CA',
    employeeCount: '1,500+',
    website: 'https://openai.com',
    fundingStage: 'Late Stage',
    remotePolicy: 'On-site preferred',
    toolsAndSystems: ['Research operations', 'Safety review', 'Customer education', 'Documentation', 'Partner support'],
  },
  'anthropic': {
    industry: 'AI / Research',
    founded: '2021',
    headquarters: 'San Francisco, CA',
    employeeCount: '500+',
    website: 'https://anthropic.com',
    fundingStage: 'Series D',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Research operations', 'Policy review', 'Customer education', 'Support operations', 'Documentation'],
  },
  'deepmind': {
    industry: 'AI / Research',
    founded: '2010',
    headquarters: 'London, UK',
    employeeCount: '1,500+',
    website: 'https://deepmind.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Research operations', 'Data review', 'Academic partnerships', 'Documentation', 'Program support'],
  },
  'huggingface': {
    industry: 'AI / ML Platform',
    founded: '2016',
    headquarters: 'New York, NY',
    employeeCount: '200+',
    website: 'https://huggingface.co',
    fundingStage: 'Series D',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Community support', 'Documentation', 'Partner programs', 'Content review', 'Education support'],
  },
  // Fintech
  'stripe': {
    industry: 'Fintech',
    founded: '2010',
    headquarters: 'San Francisco, CA',
    employeeCount: '8,000+',
    website: 'https://stripe.com',
    fundingStage: 'Late Stage',
    remotePolicy: 'Remote-friendly',
    toolsAndSystems: ['Payment operations', 'Risk review', 'Customer accounts', 'Compliance support', 'Partner support'],
  },
  'plaid': {
    industry: 'Fintech',
    founded: '2013',
    headquarters: 'San Francisco, CA',
    employeeCount: '1,500+',
    website: 'https://plaid.com',
    fundingStage: 'Series D',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Account connections', 'Customer support', 'Risk review', 'Compliance support', 'Partner operations'],
  },
  'square': {
    industry: 'Fintech',
    founded: '2009',
    headquarters: 'San Francisco, CA',
    employeeCount: '12,000+',
    website: 'https://squareup.com',
    remotePolicy: 'Remote-friendly',
    toolsAndSystems: ['Merchant support', 'Payment operations', 'Point-of-sale systems', 'Risk review', 'Customer accounts'],
  },
  'coinbase': {
    industry: 'Crypto / Fintech',
    founded: '2012',
    headquarters: 'San Francisco, CA',
    employeeCount: '3,500+',
    website: 'https://coinbase.com',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer accounts', 'Compliance support', 'Risk review', 'Fraud operations', 'Partner support'],
  },
  'robinhood': {
    industry: 'Fintech',
    founded: '2013',
    headquarters: 'Menlo Park, CA',
    employeeCount: '3,000+',
    website: 'https://robinhood.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer accounts', 'Brokerage operations', 'Risk review', 'Support operations', 'Compliance support'],
  },
  // Cloud / Infrastructure
  'cloudflare': {
    industry: 'Cloud / Security',
    founded: '2009',
    headquarters: 'San Francisco, CA',
    employeeCount: '3,500+',
    website: 'https://cloudflare.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer support', 'Security operations', 'Incident coordination', 'Account operations', 'Documentation'],
  },
  'datadog': {
    industry: 'Cloud / Monitoring',
    founded: '2010',
    headquarters: 'New York, NY',
    employeeCount: '5,000+',
    website: 'https://datadoghq.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer support', 'Incident coordination', 'Account operations', 'Usage reporting', 'Documentation'],
  },
  'snowflake': {
    industry: 'Cloud / Data',
    founded: '2012',
    headquarters: 'Bozeman, MT',
    employeeCount: '6,000+',
    website: 'https://snowflake.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer success', 'Data operations', 'Account support', 'Implementation support', 'Documentation'],
  },
  'databricks': {
    industry: 'Cloud / Data',
    founded: '2013',
    headquarters: 'San Francisco, CA',
    employeeCount: '5,500+',
    website: 'https://databricks.com',
    fundingStage: 'Late Stage',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer success', 'Data operations', 'Training', 'Implementation support', 'Documentation'],
  },
  'vercel': {
    industry: 'Cloud / Developer Tools',
    founded: '2015',
    headquarters: 'San Francisco, CA',
    employeeCount: '500+',
    website: 'https://vercel.com',
    fundingStage: 'Series D',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Documentation', 'Implementation support', 'Partner support'],
  },
  'supabase': {
    industry: 'Cloud / Developer Tools',
    founded: '2020',
    headquarters: 'San Francisco, CA',
    employeeCount: '200+',
    website: 'https://supabase.com',
    fundingStage: 'Series B',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Documentation', 'Implementation support', 'Community programs', 'Account operations'],
  },
  // E-commerce / Retail
  'shopify': {
    industry: 'E-commerce',
    founded: '2006',
    headquarters: 'Ottawa, Canada',
    employeeCount: '10,000+',
    website: 'https://shopify.com',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Merchant support', 'E-commerce operations', 'Customer accounts', 'Order management', 'Training'],
  },
  'instacart': {
    industry: 'E-commerce / Delivery',
    founded: '2012',
    headquarters: 'San Francisco, CA',
    employeeCount: '3,000+',
    website: 'https://instacart.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Shopper support', 'Retail operations', 'Delivery coordination', 'Customer accounts', 'Inventory systems'],
  },
  'doordash': {
    industry: 'Delivery / Logistics',
    founded: '2013',
    headquarters: 'San Francisco, CA',
    employeeCount: '7,000+',
    website: 'https://doordash.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Delivery operations', 'Merchant support', 'Driver support', 'Customer service', 'Logistics planning'],
  },
  // Travel / Hospitality
  'airbnb': {
    industry: 'Travel / Hospitality',
    founded: '2008',
    headquarters: 'San Francisco, CA',
    employeeCount: '6,500+',
    website: 'https://airbnb.com',
    remotePolicy: 'Remote-friendly',
    toolsAndSystems: ['Host support', 'Guest support', 'Trust operations', 'Case management', 'Marketplace operations'],
  },
  'uber': {
    industry: 'Transportation / Tech',
    founded: '2009',
    headquarters: 'San Francisco, CA',
    employeeCount: '32,000+',
    website: 'https://uber.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Driver support', 'Marketplace operations', 'Customer service', 'Safety operations', 'Logistics planning'],
  },
  'lyft': {
    industry: 'Transportation / Tech',
    founded: '2012',
    headquarters: 'San Francisco, CA',
    employeeCount: '4,000+',
    website: 'https://lyft.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Driver support', 'Rider support', 'Safety operations', 'Customer service', 'Marketplace operations'],
  },
  // Social / Communication
  'discord': {
    industry: 'Social / Communication',
    founded: '2015',
    headquarters: 'San Francisco, CA',
    employeeCount: '1,000+',
    website: 'https://discord.com',
    remotePolicy: 'Remote-friendly',
    toolsAndSystems: ['Community support', 'Trust and safety', 'Content review', 'Partner support', 'Customer education'],
  },
  'slack': {
    industry: 'Enterprise / Communication',
    founded: '2009',
    headquarters: 'San Francisco, CA',
    employeeCount: '2,500+',
    website: 'https://slack.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer success', 'Account operations', 'Implementation support', 'Training', 'Documentation'],
  },
  'zoom': {
    industry: 'Communication / Video',
    founded: '2011',
    headquarters: 'San Jose, CA',
    employeeCount: '8,000+',
    website: 'https://zoom.us',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer support', 'Account operations', 'Implementation support', 'Event support', 'Training'],
  },
  'figma': {
    industry: 'Design / Collaboration',
    founded: '2012',
    headquarters: 'San Francisco, CA',
    employeeCount: '1,500+',
    website: 'https://figma.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Design operations', 'Customer education', 'Account support', 'Community programs', 'Documentation'],
  },
  'notion': {
    industry: 'Productivity / Collaboration',
    founded: '2013',
    headquarters: 'San Francisco, CA',
    employeeCount: '500+',
    website: 'https://notion.so',
    fundingStage: 'Series C',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer education', 'Account support', 'Documentation', 'Template operations', 'Community programs'],
  },
  'linear': {
    industry: 'Productivity / Developer Tools',
    founded: '2019',
    headquarters: 'San Francisco, CA',
    employeeCount: '100+',
    website: 'https://linear.app',
    fundingStage: 'Series B',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Documentation', 'Workflow planning', 'Implementation support'],
  },
  // Security
  '1password': {
    industry: 'Security',
    founded: '2005',
    headquarters: 'Toronto, Canada',
    employeeCount: '900+',
    website: 'https://1password.com',
    fundingStage: 'Series C',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Security operations', 'Account recovery', 'Documentation', 'Implementation support'],
  },
  'crowdstrike': {
    industry: 'Cybersecurity',
    founded: '2011',
    headquarters: 'Austin, TX',
    employeeCount: '8,000+',
    website: 'https://crowdstrike.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Security operations', 'Incident coordination', 'Customer support', 'Account operations', 'Documentation'],
  },
  'paloalto': {
    industry: 'Cybersecurity',
    founded: '2005',
    headquarters: 'Santa Clara, CA',
    employeeCount: '12,000+',
    website: 'https://paloaltonetworks.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Security operations', 'Customer support', 'Incident coordination', 'Account operations', 'Training'],
  },
  // Gaming
  'roblox': {
    industry: 'Gaming / Metaverse',
    founded: '2004',
    headquarters: 'San Mateo, CA',
    employeeCount: '2,000+',
    website: 'https://roblox.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Player support', 'Creator support', 'Trust and safety', 'Community programs', 'Content operations'],
  },
  'epic': {
    industry: 'Gaming',
    founded: '1991',
    headquarters: 'Cary, NC',
    employeeCount: '4,000+',
    website: 'https://epicgames.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Player support', 'Creator programs', 'Production support', 'Community operations', 'Training'],
  },
  // Healthcare Tech
  'oscar': {
    industry: 'Healthcare / Insurance',
    founded: '2012',
    headquarters: 'New York, NY',
    employeeCount: '3,000+',
    website: 'https://hioscar.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Member support', 'Claims operations', 'Provider support', 'Care coordination', 'Compliance support'],
  },
  // Startups / Hot Companies
  'cursor': {
    industry: 'AI / Developer Tools',
    founded: '2022',
    headquarters: 'San Francisco, CA',
    employeeCount: '50+',
    website: 'https://cursor.sh',
    fundingStage: 'Series A',
    remotePolicy: 'Remote-friendly',
    toolsAndSystems: ['Customer support', 'Documentation', 'Education support', 'Account operations', 'Community programs'],
  },
  'replit': {
    industry: 'Developer Tools / Education',
    founded: '2016',
    headquarters: 'San Francisco, CA',
    employeeCount: '200+',
    website: 'https://replit.com',
    fundingStage: 'Series B',
    remotePolicy: 'Remote-friendly',
    toolsAndSystems: ['Education support', 'Customer support', 'Community programs', 'Documentation', 'Account operations'],
  },
  'railway': {
    industry: 'Cloud / Developer Tools',
    founded: '2020',
    headquarters: 'San Francisco, CA',
    employeeCount: '50+',
    website: 'https://railway.app',
    fundingStage: 'Series A',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Documentation', 'Implementation support', 'Incident coordination'],
  },
  'fly': {
    industry: 'Cloud / Developer Tools',
    founded: '2017',
    headquarters: 'Chicago, IL',
    employeeCount: '100+',
    website: 'https://fly.io',
    fundingStage: 'Series B',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Incident coordination', 'Documentation', 'Implementation support'],
  },
  'planetscale': {
    industry: 'Cloud / Database',
    founded: '2018',
    headquarters: 'San Francisco, CA',
    employeeCount: '200+',
    website: 'https://planetscale.com',
    fundingStage: 'Series C',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Documentation', 'Implementation support', 'Data operations'],
  },
  'neon': {
    industry: 'Cloud / Database',
    founded: '2021',
    headquarters: 'San Francisco, CA',
    employeeCount: '100+',
    website: 'https://neon.tech',
    fundingStage: 'Series B',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Documentation', 'Implementation support', 'Data operations'],
  },
  'turso': {
    industry: 'Cloud / Database',
    founded: '2022',
    headquarters: 'San Francisco, CA',
    employeeCount: '30+',
    website: 'https://turso.tech',
    fundingStage: 'Series A',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Documentation', 'Implementation support', 'Data operations'],
  },
};
