import type { CompanyInfo } from "../companyInfo";

export const digitalEmployers: Readonly<Record<string, Partial<CompanyInfo>>> = {
  // Large technology and online service employers
  'google': {
    industry: 'Technology',
    founded: '1998',
    headquarters: 'Mountain View, CA',
    employeeCount: '180,000+',
    website: 'https://google.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Search operations', 'Advertising tools', 'Customer support', 'Data reporting', 'Program coordination'],
  },
  'meta': {
    industry: 'Technology / Social Media',
    founded: '2004',
    headquarters: 'Menlo Park, CA',
    employeeCount: '67,000+',
    website: 'https://meta.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Content operations', 'Community support', 'Advertising tools', 'Trust and safety', 'Partner support'],
  },
  'amazon': {
    industry: 'Technology / E-commerce',
    founded: '1994',
    headquarters: 'Seattle, WA',
    employeeCount: '1,500,000+',
    website: 'https://amazon.com',
    remotePolicy: 'Varies by team',
    toolsAndSystems: ['Fulfillment operations', 'Seller support', 'Inventory systems', 'Customer service', 'Workforce scheduling'],
  },
  'microsoft': {
    industry: 'Technology',
    founded: '1975',
    headquarters: 'Redmond, WA',
    employeeCount: '220,000+',
    website: 'https://microsoft.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer success', 'Business applications', 'Support operations', 'Partner programs', 'Documentation'],
  },
  'apple': {
    industry: 'Technology / Consumer Electronics',
    founded: '1976',
    headquarters: 'Cupertino, CA',
    employeeCount: '160,000+',
    website: 'https://apple.com',
    remotePolicy: 'Mostly On-site',
    toolsAndSystems: ['Retail operations', 'Customer support', 'Product support', 'Inventory systems', 'Training'],
  },
  'netflix': {
    industry: 'Entertainment / Streaming',
    founded: '1997',
    headquarters: 'Los Gatos, CA',
    employeeCount: '13,000+',
    website: 'https://netflix.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Content operations', 'Member support', 'Production coordination', 'Localization', 'Partner support'],
  },
  // AI Companies
  'openai': {
    industry: 'AI / Research',
    founded: '2015',
    headquarters: 'San Francisco, CA',
    employeeCount: '1,500+',
    website: 'https://openai.com',
    fundingStage: 'Late Stage',
    remotePolicy: 'On-site preferred',
    toolsAndSystems: ['Research operations', 'Safety review', 'Customer education', 'Documentation', 'Partner support'],
  },
  'anthropic': {
    industry: 'AI / Research',
    founded: '2021',
    headquarters: 'San Francisco, CA',
    employeeCount: '500+',
    website: 'https://anthropic.com',
    fundingStage: 'Series D',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Research operations', 'Policy review', 'Customer education', 'Support operations', 'Documentation'],
  },
  'deepmind': {
    industry: 'AI / Research',
    founded: '2010',
    headquarters: 'London, UK',
    employeeCount: '1,500+',
    website: 'https://deepmind.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Research operations', 'Data review', 'Academic partnerships', 'Documentation', 'Program support'],
  },
  'huggingface': {
    industry: 'AI / ML Platform',
    founded: '2016',
    headquarters: 'New York, NY',
    employeeCount: '200+',
    website: 'https://huggingface.co',
    fundingStage: 'Series D',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Community support', 'Documentation', 'Partner programs', 'Content review', 'Education support'],
  },
  // Fintech
  'stripe': {
    industry: 'Fintech',
    founded: '2010',
    headquarters: 'San Francisco, CA',
    employeeCount: '8,000+',
    website: 'https://stripe.com',
    fundingStage: 'Late Stage',
    remotePolicy: 'Remote-friendly',
    toolsAndSystems: ['Payment operations', 'Risk review', 'Customer accounts', 'Compliance support', 'Partner support'],
  },
  'plaid': {
    industry: 'Fintech',
    founded: '2013',
    headquarters: 'San Francisco, CA',
    employeeCount: '1,500+',
    website: 'https://plaid.com',
    fundingStage: 'Series D',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Account connections', 'Customer support', 'Risk review', 'Compliance support', 'Partner operations'],
  },
  'square': {
    industry: 'Fintech',
    founded: '2009',
    headquarters: 'San Francisco, CA',
    employeeCount: '12,000+',
    website: 'https://squareup.com',
    remotePolicy: 'Remote-friendly',
    toolsAndSystems: ['Merchant support', 'Payment operations', 'Point-of-sale systems', 'Risk review', 'Customer accounts'],
  },
  'coinbase': {
    industry: 'Crypto / Fintech',
    founded: '2012',
    headquarters: 'San Francisco, CA',
    employeeCount: '3,500+',
    website: 'https://coinbase.com',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer accounts', 'Compliance support', 'Risk review', 'Fraud operations', 'Partner support'],
  },
  'robinhood': {
    industry: 'Fintech',
    founded: '2013',
    headquarters: 'Menlo Park, CA',
    employeeCount: '3,000+',
    website: 'https://robinhood.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer accounts', 'Brokerage operations', 'Risk review', 'Support operations', 'Compliance support'],
  },
  // Cloud / Infrastructure
  'cloudflare': {
    industry: 'Cloud / Security',
    founded: '2009',
    headquarters: 'San Francisco, CA',
    employeeCount: '3,500+',
    website: 'https://cloudflare.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer support', 'Security operations', 'Incident coordination', 'Account operations', 'Documentation'],
  },
  'datadog': {
    industry: 'Cloud / Monitoring',
    founded: '2010',
    headquarters: 'New York, NY',
    employeeCount: '5,000+',
    website: 'https://datadoghq.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer support', 'Incident coordination', 'Account operations', 'Usage reporting', 'Documentation'],
  },
  'snowflake': {
    industry: 'Cloud / Data',
    founded: '2012',
    headquarters: 'Bozeman, MT',
    employeeCount: '6,000+',
    website: 'https://snowflake.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer success', 'Data operations', 'Account support', 'Implementation support', 'Documentation'],
  },
  'databricks': {
    industry: 'Cloud / Data',
    founded: '2013',
    headquarters: 'San Francisco, CA',
    employeeCount: '5,500+',
    website: 'https://databricks.com',
    fundingStage: 'Late Stage',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer success', 'Data operations', 'Training', 'Implementation support', 'Documentation'],
  },
  'vercel': {
    industry: 'Cloud / Developer Tools',
    founded: '2015',
    headquarters: 'San Francisco, CA',
    employeeCount: '500+',
    website: 'https://vercel.com',
    fundingStage: 'Series D',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Documentation', 'Implementation support', 'Partner support'],
  },
  'supabase': {
    industry: 'Cloud / Developer Tools',
    founded: '2020',
    headquarters: 'San Francisco, CA',
    employeeCount: '200+',
    website: 'https://supabase.com',
    fundingStage: 'Series B',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Documentation', 'Implementation support', 'Community programs', 'Account operations'],
  },
  // E-commerce / Retail
  'shopify': {
    industry: 'E-commerce',
    founded: '2006',
    headquarters: 'Ottawa, Canada',
    employeeCount: '10,000+',
    website: 'https://shopify.com',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Merchant support', 'E-commerce operations', 'Customer accounts', 'Order management', 'Training'],
  },
  'instacart': {
    industry: 'E-commerce / Delivery',
    founded: '2012',
    headquarters: 'San Francisco, CA',
    employeeCount: '3,000+',
    website: 'https://instacart.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Shopper support', 'Retail operations', 'Delivery coordination', 'Customer accounts', 'Inventory systems'],
  },
  'doordash': {
    industry: 'Delivery / Logistics',
    founded: '2013',
    headquarters: 'San Francisco, CA',
    employeeCount: '7,000+',
    website: 'https://doordash.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Delivery operations', 'Merchant support', 'Driver support', 'Customer service', 'Logistics planning'],
  },
  // Travel / Hospitality
  'airbnb': {
    industry: 'Travel / Hospitality',
    founded: '2008',
    headquarters: 'San Francisco, CA',
    employeeCount: '6,500+',
    website: 'https://airbnb.com',
    remotePolicy: 'Remote-friendly',
    toolsAndSystems: ['Host support', 'Guest support', 'Trust operations', 'Case management', 'Marketplace operations'],
  },
  'uber': {
    industry: 'Transportation / Tech',
    founded: '2009',
    headquarters: 'San Francisco, CA',
    employeeCount: '32,000+',
    website: 'https://uber.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Driver support', 'Marketplace operations', 'Customer service', 'Safety operations', 'Logistics planning'],
  },
  'lyft': {
    industry: 'Transportation / Tech',
    founded: '2012',
    headquarters: 'San Francisco, CA',
    employeeCount: '4,000+',
    website: 'https://lyft.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Driver support', 'Rider support', 'Safety operations', 'Customer service', 'Marketplace operations'],
  },
  // Social / Communication
  'discord': {
    industry: 'Social / Communication',
    founded: '2015',
    headquarters: 'San Francisco, CA',
    employeeCount: '1,000+',
    website: 'https://discord.com',
    remotePolicy: 'Remote-friendly',
    toolsAndSystems: ['Community support', 'Trust and safety', 'Content review', 'Partner support', 'Customer education'],
  },
  'slack': {
    industry: 'Enterprise / Communication',
    founded: '2009',
    headquarters: 'San Francisco, CA',
    employeeCount: '2,500+',
    website: 'https://slack.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer success', 'Account operations', 'Implementation support', 'Training', 'Documentation'],
  },
  'zoom': {
    industry: 'Communication / Video',
    founded: '2011',
    headquarters: 'San Jose, CA',
    employeeCount: '8,000+',
    website: 'https://zoom.us',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer support', 'Account operations', 'Implementation support', 'Event support', 'Training'],
  },
  'figma': {
    industry: 'Design / Collaboration',
    founded: '2012',
    headquarters: 'San Francisco, CA',
    employeeCount: '1,500+',
    website: 'https://figma.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Design operations', 'Customer education', 'Account support', 'Community programs', 'Documentation'],
  },
  'notion': {
    industry: 'Productivity / Collaboration',
    founded: '2013',
    headquarters: 'San Francisco, CA',
    employeeCount: '500+',
    website: 'https://notion.so',
    fundingStage: 'Series C',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Customer education', 'Account support', 'Documentation', 'Template operations', 'Community programs'],
  },
  'linear': {
    industry: 'Productivity / Developer Tools',
    founded: '2019',
    headquarters: 'San Francisco, CA',
    employeeCount: '100+',
    website: 'https://linear.app',
    fundingStage: 'Series B',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Documentation', 'Workflow planning', 'Implementation support'],
  },
  // Security
  '1password': {
    industry: 'Security',
    founded: '2005',
    headquarters: 'Toronto, Canada',
    employeeCount: '900+',
    website: 'https://1password.com',
    fundingStage: 'Series C',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Security operations', 'Account recovery', 'Documentation', 'Implementation support'],
  },
  'crowdstrike': {
    industry: 'Cybersecurity',
    founded: '2011',
    headquarters: 'Austin, TX',
    employeeCount: '8,000+',
    website: 'https://crowdstrike.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Security operations', 'Incident coordination', 'Customer support', 'Account operations', 'Documentation'],
  },
  'paloalto': {
    industry: 'Cybersecurity',
    founded: '2005',
    headquarters: 'Santa Clara, CA',
    employeeCount: '12,000+',
    website: 'https://paloaltonetworks.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Security operations', 'Customer support', 'Incident coordination', 'Account operations', 'Training'],
  },
};
