import type { CompanyInfo } from "../companyInfo";

export const serviceAndPublicEmployers: Readonly<
  Record<string, Partial<CompanyInfo>>
> = {
  // Healthcare and care delivery
  'kaiser': {
    industry: 'Healthcare / Care Delivery',
    employeeCount: 'Large employer',
    website: 'https://www.kaiserpermanente.org',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Patient scheduling', 'Electronic health records', 'Care coordination', 'Member services'],
  },
  'mayo': {
    industry: 'Healthcare / Research',
    employeeCount: 'Large employer',
    website: 'https://www.mayoclinic.org',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Patient care', 'Clinical research', 'Scheduling', 'Care coordination'],
  },
  'cvs': {
    industry: 'Healthcare / Retail',
    employeeCount: 'Large employer',
    website: 'https://www.cvshealth.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Pharmacy systems', 'Customer service', 'Inventory', 'Benefits coordination'],
  },
  'cleveland clinic': {
    industry: 'Healthcare / Care Delivery',
    employeeCount: 'Large employer',
    website: 'https://my.clevelandclinic.org',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Patient care', 'Scheduling', 'Care coordination', 'Clinical operations'],
  },
  'hca healthcare': {
    industry: 'Healthcare / Hospital Operations',
    employeeCount: 'Large employer',
    website: 'https://hcahealthcare.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Patient registration', 'Clinical support', 'Case management', 'Hospital operations'],
  },
  'unitedhealth group': {
    industry: 'Healthcare / Insurance',
    employeeCount: 'Large employer',
    website: 'https://www.unitedhealthgroup.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Member services', 'Claims support', 'Care coordination', 'Benefits operations'],
  },
  // Retail, service, and trades
  'walmart': {
    industry: 'Retail / Operations',
    employeeCount: 'Large employer',
    website: 'https://www.walmart.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Store operations', 'Inventory', 'Customer service', 'Supply chain'],
  },
  'target': {
    industry: 'Retail',
    employeeCount: 'Large employer',
    website: 'https://www.target.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Guest service', 'Merchandising', 'Inventory', 'Fulfillment'],
  },
  'home depot': {
    industry: 'Retail / Trades',
    employeeCount: 'Large employer',
    website: 'https://www.homedepot.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Customer projects', 'Merchandising', 'Inventory', 'Pro desk support'],
  },
  'starbucks': {
    industry: 'Food Service / Retail',
    employeeCount: 'Large employer',
    website: 'https://www.starbucks.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Guest service', 'Scheduling', 'Store operations', 'Training'],
  },
  'costco': {
    industry: 'Retail / Warehouse',
    employeeCount: 'Large employer',
    website: 'https://www.costco.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Member service', 'Warehouse operations', 'Inventory', 'Merchandising'],
  },
  'lowes': {
    industry: 'Retail / Home Improvement',
    employeeCount: 'Large employer',
    website: 'https://www.lowes.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Customer projects', 'Store operations', 'Inventory', 'Pro services'],
  },
  'mcdonalds': {
    industry: 'Food Service',
    employeeCount: 'Large employer',
    website: 'https://www.mcdonalds.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Guest service', 'Store operations', 'Training', 'Scheduling'],
  },
  // Logistics, hospitality, finance, and public service
  'ups': {
    industry: 'Logistics',
    employeeCount: 'Large employer',
    website: 'https://www.ups.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Route planning', 'Package handling', 'Dispatch', 'Customer support'],
  },
  'marriott': {
    industry: 'Hospitality',
    employeeCount: 'Large employer',
    website: 'https://www.marriott.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Guest service', 'Reservations', 'Event support', 'Property operations'],
  },
  'fedex': {
    industry: 'Logistics',
    employeeCount: 'Large employer',
    website: 'https://www.fedex.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Package handling', 'Dispatch', 'Route planning', 'Customer support'],
  },
  'southwest airlines': {
    industry: 'Airlines / Travel',
    employeeCount: 'Large employer',
    website: 'https://www.southwest.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Guest service', 'Reservations', 'Airport operations', 'Scheduling'],
  },
  'hilton': {
    industry: 'Hospitality',
    employeeCount: 'Large employer',
    website: 'https://www.hilton.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Guest service', 'Reservations', 'Property operations', 'Event support'],
  },
  'state farm': {
    industry: 'Insurance',
    employeeCount: 'Large employer',
    website: 'https://www.statefarm.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Claims support', 'Customer service', 'Policy servicing', 'Sales support'],
  },
  'bank of america': {
    industry: 'Banking / Financial Services',
    employeeCount: 'Large employer',
    website: 'https://www.bankofamerica.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Customer accounts', 'Financial services', 'Risk controls', 'Branch operations'],
  },
  'city of phoenix': {
    industry: 'Government / Public Service',
    employeeCount: 'Public employer',
    website: 'https://www.phoenix.gov',
    remotePolicy: 'Varies by department',
    toolsAndSystems: ['Public service', 'Case tracking', 'Community programs', 'Resident support'],
  },
  'usps': {
    industry: 'Government / Postal Service',
    employeeCount: 'Public employer',
    website: 'https://www.usps.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Mail handling', 'Route operations', 'Customer service', 'Distribution'],
  },
  'denver public schools': {
    industry: 'Education / Public Service',
    employeeCount: 'Public employer',
    website: 'https://www.dpsk12.org',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Student support', 'School operations', 'Family services', 'Program coordination'],
  },
  'progressive': {
    industry: 'Insurance',
    employeeCount: 'Large employer',
    website: 'https://www.progressive.com',
    remotePolicy: 'Varies by role',
    toolsAndSystems: ['Claims support', 'Customer service', 'Policy servicing', 'Sales support'],
  },
};
