import type { CompanyInfo } from "../companyInfo";

export const specializedEmployers: Readonly<
  Record<string, Partial<CompanyInfo>>
> = {
  // Gaming
  'roblox': {
    industry: 'Gaming / Metaverse',
    founded: '2004',
    headquarters: 'San Mateo, CA',
    employeeCount: '2,000+',
    website: 'https://roblox.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Player support', 'Creator support', 'Trust and safety', 'Community programs', 'Content operations'],
  },
  'epic': {
    industry: 'Gaming',
    founded: '1991',
    headquarters: 'Cary, NC',
    employeeCount: '4,000+',
    website: 'https://epicgames.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Player support', 'Creator programs', 'Production support', 'Community operations', 'Training'],
  },
  // Healthcare Tech
  'oscar': {
    industry: 'Healthcare / Insurance',
    founded: '2012',
    headquarters: 'New York, NY',
    employeeCount: '3,000+',
    website: 'https://hioscar.com',
    remotePolicy: 'Hybrid',
    toolsAndSystems: ['Member support', 'Claims operations', 'Provider support', 'Care coordination', 'Compliance support'],
  },
  // Startups / Hot Companies
  'cursor': {
    industry: 'AI / Developer Tools',
    founded: '2022',
    headquarters: 'San Francisco, CA',
    employeeCount: '50+',
    website: 'https://cursor.sh',
    fundingStage: 'Series A',
    remotePolicy: 'Remote-friendly',
    toolsAndSystems: ['Customer support', 'Documentation', 'Education support', 'Account operations', 'Community programs'],
  },
  'replit': {
    industry: 'Developer Tools / Education',
    founded: '2016',
    headquarters: 'San Francisco, CA',
    employeeCount: '200+',
    website: 'https://replit.com',
    fundingStage: 'Series B',
    remotePolicy: 'Remote-friendly',
    toolsAndSystems: ['Education support', 'Customer support', 'Community programs', 'Documentation', 'Account operations'],
  },
  'railway': {
    industry: 'Cloud / Developer Tools',
    founded: '2020',
    headquarters: 'San Francisco, CA',
    employeeCount: '50+',
    website: 'https://railway.app',
    fundingStage: 'Series A',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Documentation', 'Implementation support', 'Incident coordination'],
  },
  'fly': {
    industry: 'Cloud / Developer Tools',
    founded: '2017',
    headquarters: 'Chicago, IL',
    employeeCount: '100+',
    website: 'https://fly.io',
    fundingStage: 'Series B',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Incident coordination', 'Documentation', 'Implementation support'],
  },
  'planetscale': {
    industry: 'Cloud / Database',
    founded: '2018',
    headquarters: 'San Francisco, CA',
    employeeCount: '200+',
    website: 'https://planetscale.com',
    fundingStage: 'Series C',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Documentation', 'Implementation support', 'Data operations'],
  },
  'neon': {
    industry: 'Cloud / Database',
    founded: '2021',
    headquarters: 'San Francisco, CA',
    employeeCount: '100+',
    website: 'https://neon.tech',
    fundingStage: 'Series B',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Documentation', 'Implementation support', 'Data operations'],
  },
  'turso': {
    industry: 'Cloud / Database',
    founded: '2022',
    headquarters: 'San Francisco, CA',
    employeeCount: '30+',
    website: 'https://turso.tech',
    fundingStage: 'Series A',
    remotePolicy: 'Remote-first',
    toolsAndSystems: ['Customer support', 'Account operations', 'Documentation', 'Implementation support', 'Data operations'],
  },
};
