# This file is dynamically generated by the deployment script.

terraform {
  backend "gcs" {
    bucket  = "__TF_STATE_BUCKET_NAME__" # Placeholder replaced by the script
    prefix  = "terraform/state"
  }
}
