name: Automated Dependency Updates

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:
    inputs:
      update_type:
        description: 'Select dependency update policy'
        required: true
        default: minor
        type: choice
        options:
          - minor
          - all

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-deps-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-update-python:
    name: Auto-Update Python Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Prepare Python environment
        uses: ./.github/actions/python-env
        with:
          install-deps: 'false'

      - name: Install tooling
        run: python -m pip install pur

      - name: Update minor versions
        if: github.event.inputs.update_type == 'minor' || github.event_name == 'schedule'
        run: pur -r requirements.txt --minor

      - name: Update all packages
        if: github.event.inputs.update_type == 'all'
        run: pur -r requirements.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): auto-update python dependencies"
          title: "Build: Auto-update Python dependencies"
          body: |
            ## Automated Dependency Update

            This PR was generated by a workflow to update Python dependencies.

            **Update Mode**: `${{ github.event.inputs.update_type || 'minor' }}`

            ### Next Steps
            1. Review the changes in `requirements.txt`.
            2. Run tests locally if needed.
            3. Merge after validation.

            _Auto-generated by GitHub Actions_
          branch: auto-deps-${{ github.run_number }}
          labels: dependencies, automated
          assignees: ${{ github.repository_owner }}
          reviewers: ${{ github.repository_owner }}
