name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  coverage:
    name: Code Coverage Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 1
        persist-credentials: false

    - name: Setup Python and dependencies
      uses: ./.github/actions/python-env
      with:
        python-version: '3.12'
        install-deps: 'true'
        prepare-config: 'true'

    - name: Install dev extras
      run: |
        python -m pip install -e .[dev]

    - name: Run tests with coverage
      shell: bash
      run: |
        set -euo pipefail
        pytest --cov=deploy/common/app/src/jsa --cov-report=xml --cov-report=html --cov-report=term | tee coverage-output.txt

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-html
        path: htmlcov/
        retention-days: 30
      if: always()

    - name: Coverage summary
      if: always()
      shell: bash
      run: |
        {
          echo "## 📊 Coverage Report"
          echo ""
          echo '```'
          tail -20 coverage-output.txt || echo "No coverage data available"
          echo '```'
          echo ""
          echo "Full HTML report available in artifacts."
        } >> "${GITHUB_STEP_SUMMARY}"
