name: Test macOS Local Deployment

# Run on workflow dispatch only to save costs
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'deploy/local/macos/**'
      - 'deploy/common/scripts/macos_setup.py'
      - 'deploy/common/app/src/jsa/gui_launcher.py'
      - '.github/workflows/test-macos-deployment.yml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-macos-deployment:
    name: macOS Local Deployment Test
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Setup Python 3.12
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Display Python version
        run: python3 --version

      - name: Display macOS version
        run: |
          sw_vers
          echo "macOS $(sw_vers -productVersion)"
          uname -a

      - name: Check disk space
        run: |
          df -h .
          echo "Free space: $(df -h . | awk 'NR==2 {print $4}')"

      - name: Validate macOS deployment scripts exist
        run: |
          scripts=(
            "deploy/local/macos/setup.sh"
            "deploy/local/macos/launch-gui.sh"
            "deploy/common/scripts/macos_setup.py"
            "deploy/common/app/src/jsa/gui_launcher.py"
          )

          missing=0
          for script in "${scripts[@]}"; do
            if [ ! -f "$script" ]; then
              echo "❌ Missing: $script"
              ((missing++))
            else
              echo "✅ Found: $script"
            fi
          done

          if [ $missing -gt 0 ]; then
            echo ""
            echo "❌ Missing $missing required files"
            exit 1
          fi

      - name: Validate shell scripts are executable
        run: |
          chmod +x deploy/local/macos/setup.sh
          chmod +x deploy/local/macos/launch-gui.sh
          echo "✅ Made scripts executable"

      - name: Validate Python scripts syntax
        run: |
          python3 -m py_compile deploy/common/scripts/macos_setup.py
          python3 -m py_compile deploy/common/app/src/jsa/gui_launcher.py
          echo "✅ Python scripts syntax valid"

      - name: Test setup.sh path resolution
        run: |
          # Test that the script can find the repository root
          script_path="deploy/local/macos/setup.sh"

          # Check if script navigates to repo root properly
          if grep -q "SCRIPT_DIR=" "$script_path"; then
            echo "✅ setup.sh has SCRIPT_DIR defined"
          else
            echo "⚠️  setup.sh might have path resolution issues"
          fi

          # Check if it changes to the right directory
          if grep -q "cd.*SCRIPT_DIR" "$script_path"; then
            echo "✅ setup.sh changes directory"
          fi

      - name: Test launch-gui.sh path resolution
        run: |
          # Test that the script can find the repository root
          script_path="deploy/local/macos/launch-gui.sh"

          # Check if script navigates to repo root properly
          if grep -q "SCRIPT_DIR=" "$script_path"; then
            echo "✅ launch-gui.sh has SCRIPT_DIR defined"
          else
            echo "⚠️  launch-gui.sh might have path resolution issues"
          fi

      - name: Validate shell script syntax
        run: |
          bash -n deploy/local/macos/setup.sh
          bash -n deploy/local/macos/launch-gui.sh
          echo "✅ Shell scripts syntax valid"

      - name: Install minimal dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .
          python3 -m pip install pytest

      - name: Test macos_setup.py can be imported
        run: |
          export PYTHONPATH="deploy/common/app/src"
          python3 -c "import sys; sys.path.insert(0, 'deploy/common/app/src'); print('Python path configured correctly')"

      - name: Validate macOS setup script structure
        run: |
          python3 -c '
          import sys
          from pathlib import Path
          sys.path.insert(0, "deploy/common/app/src")

          # Import the setup script to check for syntax errors
          import importlib.util
          spec = importlib.util.spec_from_file_location("macos_setup", "deploy/common/scripts/macos_setup.py")
          module = importlib.util.module_from_spec(spec)

          print("macos_setup.py is valid Python")
          '

      - name: Test macOS version requirements
        run: |
          # The script checks for macOS 12+ based on documentation
          macos_version=$(sw_vers -productVersion | cut -d '.' -f 1)
          echo "macOS major version: $macos_version"

          if [ "$macos_version" -ge 12 ]; then
            echo "✅ macOS version $macos_version is supported (12+)"
          else
            echo "⚠️  macOS version $macos_version might not be supported"
          fi

      - name: Run unit tests for macOS deployment
        run: |
          python3 -m pytest deploy/common/tests/test_macos_deployment.py -v -k "Core or test_python_version_check or test_required_packages"

      - name: Test .command files can execute
        run: |
          echo "Testing .command file executability..."
          
          # Make sure .command files are executable
          chmod +x deploy/local/macos/*.command
          chmod +x deploy/local/macos/*.sh
          
          # Test that .command files can locate their corresponding .sh files
          cd deploy/local/macos
          
          # Test setup.command can find setup.sh
          if bash -c 'SCRIPT_DIR="$(cd "$(dirname "setup.command")" && pwd)"; test -f "$SCRIPT_DIR/setup.sh"'; then
            echo "✅ setup.command can locate setup.sh"
          else
            echo "❌ setup.command cannot locate setup.sh"
            exit 1
          fi
          
          # Test launch-gui.command can find launch-gui.sh
          if bash -c 'SCRIPT_DIR="$(cd "$(dirname "launch-gui.command")" && pwd)"; test -f "$SCRIPT_DIR/launch-gui.sh"'; then
            echo "✅ launch-gui.command can locate launch-gui.sh"
          else
            echo "❌ launch-gui.command cannot locate launch-gui.sh"
            exit 1
          fi

      - name: Test setup script path resolution
        run: |
          echo "Testing setup.sh path resolution..."
          
          # Test that setup.sh can navigate to repository root
          cd deploy/local/macos
          
          # Simulate what setup.sh does
          SCRIPT_DIR="$(cd "$(dirname "setup.sh")" && pwd)"
          REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
          
          if [ -f "$REPO_ROOT/pyproject.toml" ]; then
            echo "✅ setup.sh can locate repository root"
            echo "   Repository root: $REPO_ROOT"
          else
            echo "❌ setup.sh cannot locate repository root"
            echo "   Expected pyproject.toml in: $REPO_ROOT"
            exit 1
          fi

      - name: Test macos_setup.py preflight checks
        run: |
          echo "Testing macos_setup.py preflight checks..."
          
          # Test that the setup script can run its checks
          python3 -c '
          import sys
          from pathlib import Path
          
          # Add the app source to path
          sys.path.insert(0, "deploy/common/app/src")
          
          # Import and run checks from macos_setup.py
          import importlib.util
          spec = importlib.util.spec_from_file_location("macos_setup", "deploy/common/scripts/macos_setup.py")
          module = importlib.util.module_from_spec(spec)
          spec.loader.exec_module(module)
          
          # Run preflight checks
          passed, msg = module.check_macos_version()
          print(f"macOS Check: {\"PASS\" if passed else \"FAIL\"} - {msg}")
          assert passed, f"macOS version check failed: {msg}"
          
          passed, msg = module.check_python_version()
          print(f"Python Check: {\"PASS\" if passed else \"FAIL\"} - {msg}")
          assert passed, f"Python version check failed: {msg}"
          
          passed, msg = module.check_disk_space()
          print(f"Disk Space Check: {\"PASS\" if passed else \"FAIL\"} - {msg}")
          assert passed, f"Disk space check failed: {msg}"
          
          passed, msg = module.check_internet()
          print(f"Internet Check: {\"PASS\" if passed else \"FAIL\"} - {msg}")"
          assert passed, f"Internet check failed: {msg}"
          
          print("✅ All preflight checks passed!")
          '

      - name: Test macOS deployment documentation
        run: |
          docs=(
            "deploy/local/macos/README.md"
            "docs/MACOS_QUICK_START.md"
            "docs/MACOS_TROUBLESHOOTING.md"
          )

          missing=0
          for doc in "${docs[@]}"; do
            if [ -f "$doc" ]; then
              echo "✅ Found: $doc"
            else
              echo "❌ Missing: $doc"
              ((missing++))
            fi
          done
          
          if [ $missing -gt 0 ]; then
            echo ""
            echo "❌ Missing $missing required documentation files"
            exit 1
          fi
          
          echo ""
          echo "✅ All documentation files present"

      - name: Test platform detection
        run: |
          python3 -c '
          import platform
          import sys

          print(f"Platform: {platform.system()}")
          print(f"Release: {platform.release()}")
          print(f"Version: {platform.version()}")
          print(f"Machine: {platform.machine()}")
          print(f"Python: {sys.version}")

          if platform.system() == "Darwin":
              print("Running on macOS")
          else:
              print("ERROR: Not running on macOS")
              sys.exit(1)
          '

      - name: Summary
        if: always()
        run: |
          echo ""
          echo "========================================"
          echo "  macOS Deployment Test Summary"
          echo "========================================"
          echo ""
          echo "✅ All critical checks passed!"
          echo ""
